### ISSUE TITLE
compile issue on suse.

### ISSUE THREAD

**Issue by netpipe** [buildaworldnet/IrrlichtBAW#1]
In member function ‘float irr::core::vectorSIMDf::getLengthAsFloat() const’:
/usr/lib64/gcc/x86_64-suse-linux/5/include/pmmintrin.h:56:1: error: inlining failed in call to always_inline ‘__m128 _mm_hadd_ps(__m128, __m128)’: target specific option mismatch
 _mm_hadd_ps (__m128 __X, __m128 __Y)

**Comment by devshgraphicsprogramming** [comment]
" target specific option mismatch"

Suggests that either SSE compile flags were not enabled (-msse3) or -force-inline doesnt work on suse...

What compiler version are you using?
