### ISSUE TITLE
Doxygen build seems broken

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#10]
I ran scripts/doc/irrlicht/makedocumentation.sh but didn't succeed. Here is the output:
[out.txt](https://github.com/buildaworldnet/IrrlichtBAW/files/1429729/out.txt)

**Comment by devshgraphicsprogramming** [comment]
Windows seems to have fixed it

Linux not done yet.

**Comment by devshgraphicsprogramming** [comment]
Can you try the script again?

It should have been fixed up.

**Comment by manhnt9** [comment]
Maybe some folder is missing: 
cp: target '../../../doctemp/html' is not a directory

I re-clone and run.

**Comment by devshgraphicsprogramming** [comment]
hmm it supposedly works on windows, would you mind to try make the .sh script match the .bat file?

**Comment by manhnt9** [comment]
It will not work on windows because of this line:
copy doxygen.css 
There's no doxygen.css file in scripts/doc/irrlicht to copy.

And you're generating PDF doc on linux (doxygen-pdf.cfg), which needs epstopdf (belongs to package texlive-font-utils of Ubuntu - large package). We should warn users about this.

Will send a PR, it seems working after I edit.
![screenshot_2018-06-08_09-54-18](https://user-images.githubusercontent.com/11463928/41136767-f0e995e8-6b01-11e8-8b86-88b94f775e3d.png)

**Comment by devshgraphicsprogramming** [comment]
Ok so I see documentation as PDF is no longer being made, if I can understand the scripts correctly.
