### ISSUE TITLE
Fix Doxygen PDF Documentation Generation

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#108]
Look at https://github.com/buildaworldnet/IrrlichtBAW/blob/master/scripts/doc/irrlicht/doxygen.cfg to fix https://github.com/buildaworldnet/IrrlichtBAW/blob/master/scripts/doc/irrlicht/doxygen-pdf.cfg

Especially fix the logo and name stuff

Enable the bat and sh script to take a `pdf` argument and then generate a pdf documentation instead.

**Comment by manhnt9** [comment]
As mentioned in #10, PDF generation needs epstopdf (on Ubuntu it belongs to package texlive-font-utils - over 100 MB). We may have to provide a small epstopdf binary for Windows and Linux like sed and doxygen in current repo.

**Comment by devshgraphicsprogramming** [comment]
Thats an idea, but there is a problem with cross-platform Linux binaries, they have to be compiled with really old GCC and GLIBC and Kernel to work on older systems.

Maybe it would be better to detect if `epstopdf` is available on the system and if not then ask for the path

**Comment by devshgraphicsprogramming** [comment]
could be tackled at once with #111

**Comment by devshgraphicsprogramming** [comment]
gonna use Sphinx instead

CC: @Przemog1 & @AnastaZIuk
