### ISSUE TITLE
Benchmark SSBO vs. TBO for Instanced Skinning

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#119]
Take example 07.HardwareSkinning
https://github.com/buildaworldnet/IrrlichtBAW/blob/master/examples_tests/07.HardwareSkinning/main.cpp

And extract some data such as the contents of the skinning data TBO or the SkinningManager.
It doesn't matter which frame or which dwarf, in the new benchmark/example we don't want to actually update the animation as it would add overhead which would skew the results.

Produce another example where the dwarves are drawn through instancing straight from one IMeshBuffer (NOT InstancedMeshSceneNode).

The viewProj matrix would be provided using a UBO.
(Use **device local** memory with either orphaning or staging buffer).

Then get the extracted data of bone transformation matrices for a dwarf from the previous example, to set up a static immutable IGPUBuffer in GPU memory with no update possibility.
Of course for N instances the bone transform data would need to be duplicated N times, and the bone pose transformations would be premultiplied by the per-instance transformation matrices.

What we are benchmakring is the best way to provide the data to the instanced dwarf vertex shader:
1. As a TBO (same as in the 07.HardwareSkinning case, but with a big offset based on `gl_InstanceID`) [a.k.a. typeless]
2. As a `packed` (nothing in the sense of std430 packing) SSBO (all the bone transform data in one data range for one instance)
3. As a weak Structure of Arrays SSBO (separate arrays of world and normal matrices indexed by `gl_InstanceID`)
4. As a strong Structure of Arrays SSBO (split even the mat4 and mat3 into separate arrays of vec4 indexed in the same way as in 3)
5. As a ridiculously strong Structure of Arrays SSBO (split the mat4 and mat3 into separate arrays of individual floats indexed in the same way as in 3)

Use standard techniques for reducing rasterizer and pixel shader workload:
1) 64x64 View port
2) Depth only FBO
3) RasterizerDiscard flag enable

**Comment by devshgraphicsprogramming** [comment]
Rasterizer Discard gets optimized away on some dirvers, so don't use

**Comment by devshgraphicsprogramming** [comment]
allow for a _DEBUG_VIEW define where you render to screen with colours so we can see it works

**Comment by devshgraphicsprogramming** [comment]
@Crisspl whats the status on this, does it compile and run on the new master branch?

**Comment by Crisspl** [comment]
i have to fix it a little because I lost the file with skinning data dump

**Comment by devshgraphicsprogramming** [comment]
ok

**Comment by devshgraphicsprogramming** [comment]
@Crisspl can you fix this?

**Comment by devshgraphicsprogramming** [comment]
We only need to benchmark SSBO (TBO is irrelevant and old case 5).

Note: Either go wide or go home, basically either load `float` or `vec4` (or bigger) no half-measures!
** NEVER EVER USE A `vec3` !!!!! **

Backed up by 
https://github.com/sebbbi/perftest

Navi prefers "random" loads to be wide (as many bytes as possible), unless they are unaligned UTB/TBO loads.
If you need to use a single scalar (because it a PDF/CDF or binary search) SSBO will be fastest and UTB/TBO same speed.

Turing vastly improved the raw load L1 performance.
Turing prefers "random" loads to some from SSBO by a large margin over UTB/TBO.
Turing starts topping out with perf on big vectors (> 64bit per element) for any load, but does not care about alignment.
If you need to use a single scalar (because it a PDF/CDF or binary search) SSBO will be fastest and UTB/TBO same speed.


** Special Note: ** Turing does not automatically use subgroup ops to "broadcast" a uniform value loaded from the same SSBO address, you better use a UBO or UTB for that. And Navi SSBO is faster than UBO for all vector types. If using subgroup intrinsics Turing could be faster with SSBO than UBO.


So we only need to consider:
1. As a packed (nothing in the sense of std430 packing) SSBO (all the bone transform data in one data range for one instance)
2. As a weak Structure of Arrays SSBO (separate arrays of world and normal matrices indexed by gl_InstanceID)
3. As a strong Structure of Arrays SSBO (split even the mat4 and mat3 into separate arrays of vec4 indexed in the same way as in 3)
