### ISSUE TITLE
AddInstance Crash

### ISSUE THREAD

**Issue by Cop46** [buildaworldnet/IrrlichtBAW#12]
Hi, I have tried to test your IrrlichtBaw engine but there is a crash on the node->addInstance(mat); when I execute the sample 08.HardwareInstancing.
I work with Irrlicht for a few years and I want to make some landscape with trees and grass ans I think instancing is the right way.
Compiled under Visual Studio 2015 without problems.
Maybe you know where is the problem.
Thanks for your good work :)

**Comment by devshgraphicsprogramming** [comment]
I'm sorry but this example works on both Linux and Windows in our
environments. Could you provide a stack dump and details about your machine?

**Comment by Cop46** [comment]
crash is at if (!instanceDataBuffer->Alloc(instanceIDs,instanceCount)) at line 284 on CMeshSceneNodeInstanced.cpp only in release mode. In debug mode that work perfect.
My computer is an intel I5-2400 with 10Gb of ram and with Nvidia GTX770 under win7 SP1 64bits.
I Don't know how send you a dump of the stack. the .dmp file I have take 113Mo.

VStudio say :
Exception levée : violation d'accès en lecture.

this->instanceDataBuffer a été nullptr.

**Comment by Cop46** [comment]
assert(node->setLoDMeshes(LevelsOfDetail,28*sizeof(float),cullingXFormFeedbackShader,vaoSetupOverride,2,NULL,0,CPUCullingFunc));
This is assert the problem...
Line 428 main.cpp

**Comment by devshgraphicsprogramming** [comment]
Aaah yeah, MSVC has no assert and there is some workaround as a preprocessor (#define) function which makes the code inside the assert disappear in release builds.

need to do

bool success = node->setLoDMeshes....
assert(success);

you can either make a pull request or wait for me to commit a fix in 2 days

**Comment by Cop46** [comment]
No problems ! I'm really impressed by the speed of render with hardware instancing !
You have made a good work :)

**Comment by devshgraphicsprogramming** [comment]
Committed a fix
