### ISSUE TITLE
Add an online GLSL to SPIR-V compiler

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#129]
We have a choice between shaderc and glslang.

However shaderc wraps around both glslang and SPIRV-Tools while providing `#include` functionality.

the asset::IAssetManager should load an asset::ISPIR_VProgram

**Comment by manhnt9** [comment]
[Using Glslang as an Online Compiler for Vulkan](http://forestsharp.com/glslang-cpp/)

**Comment by devshgraphicsprogramming** [comment]
Thanks for the link, it talks about shaderc too

I prefer shaderc because of the integration of SPIRV-Tools and the include stuff

**Comment by devshgraphicsprogramming** [comment]
https://www.khronos.org/assets/uploads/developers/library/2016-vulkan-devday-uk/4-Using-spir-v-with-spirv-cross.pdf

[Under Vulkan]
It is paramount that the GLSL compiler reports all enabled Vulkan extensions in the form of '#define's to the shader (insert in the line just after '#version').

I.e. if the vulkan device was created with the supported extension `KHR_shader_subgroup_arithmetic` then the GLSL compiler must insert '#define GL_KHR_shader_subgroup_arithmetic' into every GLSL source before compilation to SPIRV.

This is so things like this can be done
```
#ifndef KHR_shader_subgroup_arithmetic
    #extension GL_NV_shader_thread_group: enable
#endif // KHR_shader_subgroup_arithmetic
```

**Comment by devshgraphicsprogramming** [comment]
https://repository.genmymodel.com/devshgraphicsprogramming/VulkanShaders

**Comment by devshgraphicsprogramming** [comment]
When we migrate to SPIR-V only our built-in material shaders will need converting to SPIR-V.

However they (and a bunch of other dependencies) should be embedded in the library and not depend on some file being found.
https://github.com/vector-of-bool/cmrc

**Comment by devshgraphicsprogramming** [comment]
This has now turned into a duplicate of #130
