### ISSUE TITLE
Fix all Wswitch warnings (case not handled)

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#144]
its a very simple error to fix.

**Comment by devshgraphicsprogramming** [comment]
E_FORMAT has a lot of these

https://github.com/buildaworldnet/IrrlichtBAW/issues/179#issuecomment-466755106

**Comment by devshgraphicsprogramming** [comment]
@manhnt9 once you fix the Linux CMake, can you paste the `VERBOSE` output log here (or upload it)?

**Comment by manhnt9** [comment]
You mean the full console output running CMake and make?

**Comment by devshgraphicsprogramming** [comment]
yep, at least the part that counts Warnings and Errors

**Comment by manhnt9** [comment]
Full log (including make's) is too long to read. Gonna paste CMake's output and warning counts of the project.

**Comment by manhnt9** [comment]
cmake .. -DIRR_PCH=OFF
-- The CXX compiler identification is GNU 7.3.0
-- The C compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- SPIRV-Tools: nosetests was not found - python support code will not be tested
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.15", minimum required is "2.7") 
-- optimizer enabled
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Shaderc: build type is "Release".
-- Configuring Shaderc to avoid building tests.
-- nosetests was not found - python code will not be tested
-- asciidoctor was not found - no documentation will be generated
-- Found Git: /usr/bin/git (found version "2.17.1") 
DIST_NAME: libjpeg
DIST_VERSION: 9.1.0
DIST_LICENSE: jpeg license
DIST_AUTHOR: Tom Lane, Guido Vollbeding, Philip Gladstone, Bill Allombert, Jim Boucher, Lee Crocker, Bob Friesenhahn, Ben Jackson, Julian Minguillon, Luis Ortiz, George Phillips, Davide Rossi, Ge
DIST_MAINTAINER: Peter Kapec
DIST_URL: http://www.ijg.org/
DIST_DESC: Independent JPEG Group
DIST_DEPENDS: 
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test HAVE_LD_VERSION_SCRIPT
-- Performing Test HAVE_LD_VERSION_SCRIPT - Success
-- Symbol prefix: 
CMake Warning (dev) at /home/manh/cmake_bin/share/cmake-3.13/Modules/FindOpenGL.cmake:270 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  source/Irrlicht/CMakeLists.txt:2 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found Vulkan: /usr/lib/x86_64-linux-gnu/libvulkan.so  
-- Building with Vulkan driver
-- Configuring done
CMake Error at CMakeLists.txt:72 (add_compile_options):
  Error evaluating generator expression:

    $<$CONFIG:DEBUG>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  source/Irrlicht/CMakeLists.txt:175 (irr_adjust_flags)


CMake Error at CMakeLists.txt:72 (add_compile_options):
  Error evaluating generator expression:

    $<$CONFIG:DEBUG>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  source/Irrlicht/CMakeLists.txt:175 (irr_adjust_flags)


CMake Error at CMakeLists.txt:72 (add_compile_options):
  Error evaluating generator expression:

    $<$CONFIG:DEBUG>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  source/Irrlicht/CMakeLists.txt:175 (irr_adjust_flags)


CMake Error at CMakeLists.txt:72 (add_compile_options):
  Error evaluating generator expression:

    $<$CONFIG:DEBUG>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  source/Irrlicht/CMakeLists.txt:175 (irr_adjust_flags)


-- Generating done
-- Build files have been written to: /home/manh/IrrlichtBAW/build

Total warnings in Code:Blocks (Unix Makefiles): 4640

**Comment by devshgraphicsprogramming** [comment]
Ok, but those are CMake Configure&Generate warnings... not build warnings (or counts)

**Comment by manhnt9** [comment]
The last line of the comment is build warning counts.
Do you need the full warning logs of CodeBlocks as well?

**Comment by devshgraphicsprogramming** [comment]
No, but I'd like to see a `greped` list of lines with `-Wswitch` for the purpose of this issue.

P.S. Also knowing how many warnings come from the Irrlicht project itself and not its dependencies.
P.P.S. Am I right looking at the above that the "Debug" configuration was used?

**Comment by manhnt9** [comment]
OK, understood, will dig those info more thoroughly later.

**Comment by devshgraphicsprogramming** [comment]
There are over 2100 warnings from `-Wswitch`

This problem is usually from not having a `default` clause in a switch.

@Crisspl the following switches don't handle all cases:
- src/irr/asset/ICPUShader.cpp:246,382
- a multitude in src/irr/asset/CMeshManipulator.cpp

@others
There are some switches that are about unhandled formats (no default clause) in ImageWriters

CColorConverter is a bit harder to fix, we shouldn't fix it as we want to delete it (and kill software driver).

**Comment by Crisspl** [comment]
Probably resolved https://github.com/buildaworldnet/IrrlichtBAW/commit/fa0739877510034f55211ce95cb9ec723577efe2

**Comment by devshgraphicsprogramming** [comment]
Closing, but @Florastamine please compile your stuff in Debug and check for Wswitch coming from image classes.
