### ISSUE TITLE
Override global new and delete operators with an optional disable switch

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#146]
Also have a switch whether to allow them to throw

https://en.cppreference.com/w/cpp/memory/new/operator_new
https://en.cppreference.com/w/cpp/memory/new/operator_delete

https://stackoverflow.com/questions/7194127/how-should-i-write-iso-c-standard-conformant-custom-new-and-delete-operators

This could however be an inconvenience as I presume irrlicht would have to be linked first to override ::new and ::delete

**Comment by devshgraphicsprogramming** [comment]
is this even a good idea?

**Comment by manhnt9** [comment]
It could affect both user's code and your new/delete strategy.
Providing your own new and delete functions in your own namespace and using them would be better.

**Comment by devshgraphicsprogramming** [comment]
> It could affect both user's code and your new/delete strategy.
We already provide these, maybe some nice forwarding placement new function with constructor arguments would be good.

I'm not concerned about affeting user's code.. more about linking mess for the user.

**Comment by devshgraphicsprogramming** [comment]
Yeah not a good idea, we can revisit if we need.

For now class overloads are all we need.
