### ISSUE TITLE
AES128 encryption on the BAW asset saver/loader

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#15]
EVP_aes_128_gcm to be used to encrypt the data of the Blobs

https://wiki.openssl.org/index.php/EVP_Symmetric_Encryption_and_Decryption#C.2B.2B_Programs

OpenSSL to be moved into Irrlicht as a dependency
(could do same with lz4 and lzma)

**Comment by devshgraphicsprogramming** [comment]
Almost merged

**Comment by cloudygeek** [comment]
don't do with openssl, just use chilkat

**Comment by devshgraphicsprogramming** [comment]
already done, plus chillkat cannot go into this repository
