### ISSUE TITLE
Convert all options of IrrCompileConfig.h to CMake

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#155]
This helps user configure the library easier and doesn't mess with the code.
PR submitting won't bring more problems because developer can use different build configurations.

**Comment by devshgraphicsprogramming** [comment]
This could be a thing we could do, I'll put it on our TODO list but not
for the 0.3 release.

Unless you manage to do it before us, in which case I'm happy to accept
a PR to cmake.

**Comment by devshgraphicsprogramming** [comment]
I'm actually +1 for this after my recent CMake experiences

**Comment by devshgraphicsprogramming** [comment]
@manhnt9 , there's only one slight problem... those options would still have to remain `#define`s as the code that's using the library needs to know (at compile time) if the library was compiled with feature XYZ

Any way for CMake to make a config header with all the defines? Also where the f*** would it install to then?

**Comment by Crisspl** [comment]
>those options would still have to remain #defines as the code that's using the library needs to know (at compile time) if the library was compiled with feature XYZ

I believe this can be done with https://cmake.org/cmake/help/v3.0/command/configure_file.html

**Comment by devshgraphicsprogramming** [comment]
well, yeah but then the entire set of includes has to be "installed" somewhere.

**Comment by manhnt9** [comment]
I've seen some popular libraries which install a configure header with in their include paths. These things are considered normal. I use CMake's configure_file feature and have single CMake-generated configure header used in build and installation too.

**Comment by devshgraphicsprogramming** [comment]
Closed #195 , discussion from https://github.com/buildaworldnet/IrrlichtBAW/issues/195#issuecomment-461221512 should move to here.

**Comment by manhnt9** [comment]
You guys could try building CEGUI since it is a great CMake legacy example in my opinion. So you would know how to improve IrrBAW's script. Users could use CMake GUI (or pass command line options) to enable/disable all or each examples instead of cd to example folders and build them manually.

**Comment by devshgraphicsprogramming** [comment]
Well a single solution for all examples would be good, except that not every IDE supports the concept of a "workspace" like CodeLite or Visual Studio

**Comment by devshgraphicsprogramming** [comment]
Ok we should probably use something like this
```
set_target_properties(mylib PROPERTIES PUBLIC_HEADER "some.h;another.h")
INSTALL(TARGETS mylib 
        LIBRARY DESTINATION some/libpath
        PUBLIC_HEADER DESTINATION some/includepath
)
```

So user COULD install the stuff to system-wide directories and end up with `/usr/local/lib/libIrr*.a` and `usr/local/include/irr/*`
(I think cmake-gui default configure is `/usr/local` on Linux).


However what I really want to be able to do is:
1. Install my headers into `./someDirectory/Platform/BuildType/` (can be  `./someDirectory/Platform/BuildType/include`)
2. Install my library into `./someDirectory/Platform/BuildType/` (I would rather not have it be  `./someDirectory/Platform/BuildType/lib`)

Obviously:
 - `someDirectory`is a directory of my choosing in the repository root 
 - `Platform` is the OS, so Android/Linux/Windows
 - `BuildType` is the build config, so Debug/Release/ etc.


Essentially both set-ups have to work, usual Linux system-wide and my organised per-platform, per-build-type co-existing set-up.

**Comment by devshgraphicsprogramming** [comment]
Due to #196 we should have a `config.h` per-namespace (so 7 config files overall)
These per-namespace config files should include all external headers in their namespace.

There config files should all be included into `include/irr/irrlicht.h`, which itself is not configured
(Then `irrlicht.h` can be used as a pre-compiled header, or in a pre-compiled header for external projects)

Also for reference
https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/

**Comment by Crisspl** [comment]
Are there any options in `IrrCompileConfig.h` that should be deleted?

**Comment by devshgraphicsprogramming** [comment]
Btw. regarding my INSTALL paths rules ( https://github.com/buildaworldnet/IrrlichtBAW/issues/155#issuecomment-466954131 ) , I've came across something this
```cmake
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
	set(CMAKE_INSTALL_PREFIX "${PROJECT_SOURCE_DIR}/our/own/path" CACHE PATH "default install path" FORCE )
endif()
```

**Comment by devshgraphicsprogramming** [comment]
> Are there any options in IrrCompileConfig.h that should be deleted?

hmm, well I wouldn't delete, I would just hide some of them:
1. Everything Up to line 154 (actually 172, those descriptor set maximums I wouldn't like to touch/expose until we get out shaders sorted out and xform feedback removed)
2. The stuff about X11, XRandr etc. as that will be replaced wholly by SDL2

to expose 100%
```
Compile with OPENGL, VULKAN, BURNINGS VIDEO
Lines 238-270
```

to actually delete:
```
NO_IRR_COMPILE_WITH_JOYSTICK_EVENTS_ = always true // because we will use SDL2 for rumble
_XBOX // that stuff was for the original xbox
actually everything to do with XBOX, DIRECT3D, DIRECTX and Solaris
_IRR_COMPILE_WITH_CONSOLE_DEVICE_ = always true // because we always want console device to be available
_IRR_OPENGL_USE_EXTPOINTER_ = always true // just define it on top of COpenGLExtensionHandler.h
_IRR_USE_NVIDIA_PERFHUD_ // that thing is dead
https://github.com/buildaworldnet/IrrlichtBAW/blob/master/include/IrrCompileConfig.h#L531
Whatever else you think it justified, just let me know
```

Plus lots of stuff is automatic and derived (from platform and build type).
`#define __IRR_COMPILE_WITH_X86_SIMD_` should actually be defined automatically if the build is not for ARM.
When I say automaticall defined = conditionaly defined

But we should definitely add `#define _IRR_DEBUG` when the config is debug

P.S. Don't touch the `NEW_MESHES` define
P.P.S. We should probably change the version defined and the SDK string to match our versioning convention (we are at 0.3.0-beta).

**Comment by devshgraphicsprogramming** [comment]
@Crisspl a few wishes I have for the Linux CMake:
1. Add `-Wno-error=ignored-attributes` compiler option only when GGC is 6.1+ (or 6+)
2. Add CMAKE variable to enable `-fsanitize=address` (default is off)
3. Add CMAKE variable to enable `-fsanitize=thread` (default is off)

The above should be options to apply at the top level (to the tools, lib and examples)

**Comment by devshgraphicsprogramming** [comment]
We should disable installing for a number of the 3rdparty dependencies as well as set the correct defaults (like don't install shaderc, SPIR-V and don't build their tools and executables)

**Comment by devshgraphicsprogramming** [comment]
About the SIMD configure defines. We should replace
```c++
#define __IRR_COMPILE_WITH_X86_SIMD_

#ifdef __IRR_COMPILE_WITH_X86_SIMD_
#define __IRR_COMPILE_WITH_SSE3

#include <immintrin.h>

#ifdef __SSE3__
#define __IRR_COMPILE_WITH_SSE3
#endif

#ifdef __SSE4_1__
#define __IRR_COMPILE_WITH_SSE4_1
#endif
```
with (obviously `_IRR_COMPILE_FOR_ARM ` must be defined in an installed config header in the future)
```c++
#ifdef _IRR_COMPILE_FOR_ARM // name it better
    #define __IRR_COMPILE_WITH_ARM_SIMD_ // NEON
#else 
    #define __IRR_COMPILE_WITH_X86_SIMD_ // SSE 4.2 
    #include <immintrin.h>
#endif
```

You can take `__IRR_COMPILE_WITH_X86_SIMD_` to replace and mean `__IRR_COMPILE_WITH_SSE4_2`,`__IRR_COMPILE_WITH_SSE4_1` and `__IRR_COMPILE_WITH_SSE3_0` at the same time.

The AVX stuff you can comment out and leave hanging around for the near future.

**Comment by devshgraphicsprogramming** [comment]
`IRRLICHT_FAST_MATH` should be renamed to `__IRR_FAST_MATH` and like `_IRR_DEBUG` (or `__IRR_DEBUG_BUILD`, whatever you choose) be defined and installed in the configured header (as the definitions of  inline functions depend on this)

**Comment by devshgraphicsprogramming** [comment]
We should also pick a convention for defines `_IRR*` or `__IRR*` and stick to it.

Maybe 1 underscore for an installed define in a configure header made by CMAKE and 2 underscores for a derived (from CMake options and 3rdparty defines and compiler defines) preprocessor token, such as `__IRR_COMPILE_WITH_AVX`.

Then this whole thing could be split into 2 orderly files:
1. Installed&Configured `BuildConfigOptions.h` with the CMake configured defines
2. Static and unchanging `AutoConfig.h` with the `#ifdef`s that derive other options

**Comment by devshgraphicsprogramming** [comment]
Conversation in #265 supercedes this
