### ISSUE TITLE
beginScene clears the front buffer somehow

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#159]
I and @devshgraphicsprogramming experimented several things and found out that beginScene is clearing the front buffer.

RenderDoc v0.92 capture file
[beginScene.zip](https://github.com/buildaworldnet/IrrlichtBAW/files/2526039/beginScene.zip)

Investigation: find out why COpenGLDriver::clearScreen() call from beginScene accidentally clears the front buffer. Maybe ```extGlClearNamedFramebufferfv``` implementation did, potentially a driver bug.

```cpp
void COpenGLDriver::clearScreen(const E_SCREEN_BUFFERS &buffer, const float* vals)
{
    switch (buffer)
    {
        case ESB_BACK_LEFT:
            extGlClearNamedFramebufferfv(0,GL_COLOR,0,vals);
            break;
        case ESB_BACK_RIGHT:
            extGlClearNamedFramebufferfv(0,GL_COLOR,0,vals);
            break;
        case ESB_FRONT_LEFT:
            extGlClearNamedFramebufferfv(0,GL_COLOR,0,vals);
            break;
        case ESB_FRONT_RIGHT:
            extGlClearNamedFramebufferfv(0,GL_COLOR,0,vals);
            break;
    }
}
```

Proposed solution: removing clearScreen ability of beginScene call, requires modification for all examples.

OS: Ubuntu 18.04
Driver: NVIDIA 410.73
GPU: GTX 1050 Ti

**Comment by ahuillet** [comment]
Can you please provide apitrace instead, or if a renderdoc capture, one generated with a recent build of renderdoc? But apitrace is a better tool for investigating suspected GL driver bugs because it guarantees the order of GL calls.

**Comment by devshgraphicsprogramming** [comment]
yeah will work on getting you an API-trace, we need to isolate the bug to a simple example.

RenderDoc won't actually show you the bug on replay because it only captures one frame at a time.
ApiTrace is an option (does it caputre GLX too?).

The bug is basically:
```
// Bind custom FBO before rendering

// During rendering loop
glClearNamedFramebufferfv on the default framebuffer GL_COLOR , 0 to black
glClearNamedFramebufferfv on custom FBO GL_DEPTH attachment to far value
render geometry to FBO
glBlitNamedFramebuffer from FBO to default framebuffer
swapBuffers
```

**Comment by devshgraphicsprogramming** [comment]
A compiled ubuntu binary is available here
https://github.com/buildaworldnet/IrrlichtBAW/tree/master/examples_tests/09.FrontClearingBug/bin

It doesn't cause a problem for me at all, hence why I closed the issue... no apitrace.

But if that binary causes a problem for @manhnt9 then he can post his Apitrace

**Comment by ahuillet** [comment]
Do you still suspect that there is a NVIDIA driver bug?

**Comment by devshgraphicsprogramming** [comment]
If @manhnt9 still gets it **without** the engine logging that "double buffering is not available", then yes.

But I doubt it will.

**Comment by manhnt9** [comment]
I only see white screen. Log:
```
Irrlicht Engine version 1.8.3-baw
Linux 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64
Creating X window...
Using renderer: OpenGL 4.5.0
GeForce GTX 1050 Ti/PCIe/SSE2: NVIDIA Corporation
GLSL version: 45.0
```
On NVIDIA 390.87

**Comment by devshgraphicsprogramming** [comment]
That's correct behaviour, there is no bug then.

You were probably using a visual without double buffering when experiencing the problem.

**Comment by manhnt9** [comment]
What's happening with createDevice?

**Comment by devshgraphicsprogramming** [comment]
https://github.com/buildaworldnet/IrrlichtBAW/blob/08269e8af602b0622b2b48cad785d0997f0b4551/source/Irrlicht/Irrlicht.cpp#L40

TBF thats a legacy function and should be removed
