### ISSUE TITLE
Shader uniform count is limited to 4

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#160]
Fragment shader:
```c
#version 420 core

layout(binding = 0) uniform sampler2D tex0;
layout(binding = 1) uniform sampler2D tex1;
layout(binding = 2) uniform sampler2D tex2;
layout(binding = 3) uniform sampler2D tex3;

uniform float metallic;
uniform float roughness;
```

Material Callback:
```cpp
void DefaultShader::PostLink(irr::video::IMaterialRendererServices* services, const irr::video::E_MATERIAL_TYPE& materialType,
  const irr::core::array<irr::video::SConstantLocationNamePair>& constants) {
  for (size_t i = 0; i < constants.size(); ++i) {
    const auto& constant = constants[i]; // break-point shows that there's no constant named metallic
    if (constant.name == "MVP") { // vertex shader uniform, 
      m_mvpUniform = constant.location; // reach this line
      m_mvpUniformType = constant.type; // reach this line
    } else if (constant.name == "WorldView") {
      m_worldViewUniform = constant.location; // reach this line
      m_worldViewUniformType = constant.type; // reach this line
    } else if (constant.name == "metallic") {
      int a = 100; // can't reach this line
    }
  }
}
```

Tried with vertex shader:
```c
#version 420 core

layout(location = 0) in vec4 in_position;
layout(location = 2) in vec2 in_uv;
layout(location = 3) in vec4 in_normal;

uniform mat4 MVP;
uniform mat4 WorldView;
uniform float metallic;
```

The result is the same if put uniform declaration in vertex shader or fragment shader.

**Comment by manhnt9** [comment]
However, trying ```uniform mat4 metallic``` won't work also.
It's like uniform count is limited to 4 somehow.
Declaring more uniforms always give the following content of constants array:
MVP, WorldView, tex0, tex1

Stepping debugger into the ```COpenGLSLMaterialRenderer::init```
activeUniformCount is always 4
Tried disabling ```_IRR_OPENGL_USE_EXTPOINTER_```
and use ```glGetProgramInterfaceiv```, still get only 4 uniform count.

**Comment by manhnt9** [comment]
I think I'm having a really bad driver from NVIDIA
My metallic and roughness textures are loaded but never bound to a shader.
Checking with renderdoc shows only tex0 and tex1, which are exactly the same with constants array.
So the real question is: I'm having 4 uniform limit.
Trying another driver version.

**Comment by manhnt9** [comment]
Currently on NVIDIA 390.87, same problem.

**Comment by manhnt9** [comment]
setMaterialTexture called 4 times, still only 2 textures are bound in shader
textures is a vector storing handles of successfully loaded texture by IVideoDriver

![screenshot_2018-10-30_12-35-07](https://user-images.githubusercontent.com/11463928/47698061-5a8ce180-dc40-11e8-832d-40af70d0e9f6.png)

**Comment by manhnt9** [comment]
Same problem on my laptop with NVIDIA 390.77
GTX 960MX
Ubuntu 18.04

**Comment by manhnt9** [comment]
I acknowledged that in shader, if a texture is not used, it will not appear in renderdoc.
After commenting out my other textures (tex2, tex3), I still can't reach float uniforms in fragment shader.

**Comment by manhnt9** [comment]
This is really confusing. I must use the uniform in shader code in order to have it in PostLink.
I do understand that this is because OpenGL itself.
Solved.

**Comment by devshgraphicsprogramming** [comment]
> I must use the uniform in shader code in order to have it in PostLink.

As per the GL spec
