### ISSUE TITLE
Can not find GLX on Ubuntu 18.04 NVIDIA

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#161]
I was using createDevice instead of createDeviceEx for the whole time because of this error.

Relates #159 and may be causing #160.

![screenshot_2018-10-30_13-28-56](https://user-images.githubusercontent.com/11463928/47700114-ddfe0100-dc47-11e8-8854-a1602a82f865.png)

This function is returning null:
```cpp
fbc = glXChooseFBConfig(display, DefaultScreen(display), visualAttrBuffer, &fbcount);
```

Happens both on PC with NVIDIA's installer and Laptop with Ubuntu's Additional Driver Installer.

**Comment by manhnt9** [comment]
Solved by changing:
```cpp
  params.Bits = 32;
  params.ZBufferBits = 32;
```
to
```cpp
  params.Bits = 24;
  params.ZBufferBits = 24;
```

#160 is still there, I can't use my float uniform.

**Comment by devshgraphicsprogramming** [comment]
Funny, seems your window manager doesn't support transparent windows... what are you on Wayland or X11?

**Comment by devshgraphicsprogramming** [comment]
Semi-related and a reverse bug #4 (actually a feature => transparent windows)

**Comment by manhnt9** [comment]
I'm on X11
