### ISSUE TITLE
Improve upstream buffer API

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#167]
```cpp
    upStreamBuff->multi_place(2u, (const void* const*)m_lineData,(uint32_t*)&offsets,(uint32_t*)&sizes,(uint32_t*)&alignments);
    if (upStreamBuff->needsManualFlushOrInvalidate())
    {
        auto upStreamMem = upStreamBuff->getBuffer()->getBoundMemory();
        m_driver->flushMappedMemoryRanges({video::IDriverMemoryAllocation::MappedMemoryRange(upStreamMem,offsets[0],sizes[0]),video::IDriverMemoryAllocation::MappedMemoryRange(upStreamMem,offsets[1],sizes[1])});
    }
```

If `needsManualFlushOrInvalidate` is always called after `multi_place`, can we move this call inside `multi_place` so that user doesn't have to call it manually?

**Comment by devshgraphicsprogramming** [comment]
Not really because Vulkan can flush multiple mapped memory ranges in a single device command, so flushes from multiple placements and user-side modifications can be performed "at-once"

**Comment by devshgraphicsprogramming** [comment]
Even ranges from different buffers can be flushed in one call
