### ISSUE TITLE
Possible free bug in example?

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#170]
Should this be `multi_free(2u, ...` since the above is `multi_place(2u, ...`?
https://github.com/buildaworldnet/IrrlichtBAW/blob/5b97e0df68fa6849bf550b6809bcdc682b75640e/examples_tests/03.GPU_Mesh/main.cpp#L203

https://github.com/buildaworldnet/IrrlichtBAW/blob/5b97e0df68fa6849bf550b6809bcdc682b75640e/examples_tests/03.GPU_Mesh/main.cpp#L231

**Comment by devshgraphicsprogramming** [comment]
Wow, yes it should be!

Submit a PR fix?

**Comment by manhnt9** [comment]
I was going to but my editor changed many line endings of that particular file.
Is it considered too much change?
