### ISSUE TITLE
Things to fix as noted by @baldurk

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#174]
> * `include/irr/core/alloc/address_allocator_traits.h(80)`: `supportsArbitraryOrderFrees` isn't available in one template instantiation where `AddressAlloc=irr::scene::IMeshSceneNodeInstanced::InstanceDataAddressAllocator`.
> 
> * `include/irr/core/alloc/address_allocator_traits.h(139)`: the `std::declval<U&>().template multi...` syntax really confused the compiler. Removing the `template` worked but I'm sure that's not the right fix.
> 
> * `include/irr/core/alloc/HeterogenousMemoryAddressAllocatorAdaptor.h(95)`: `HeterogenousMemoryAddressAllocatorAdaptor` inheriting `AddressAllocator` as `private` broke later in `ResizableHeterogenousMemoryAllocator::multi_free_addr` that expected to access `AddressAllocator::reserved_size` which was inaccessible. Changing to `public` inheritance fixed it.
>

**Comment by devshgraphicsprogramming** [comment]
Notes:

1. ArbitraryOrderFrees should instantiate nicely due to SFINAE
2. Cannot remove the `template` as that template meta-function checks whether a **only** templated forwarding declaration of that method is available
3. The inheritance should work, reserved_size is a static function!

**Comment by devshgraphicsprogramming** [comment]
I wonder if the last issue would be fixed by prepending `typename` before the static function call

**Comment by Crisspl** [comment]
well, if inheritance is private than you don't have access to base's members. Regardless they're static or not afaik. So that's all. So... friendship or rethink this somehow I guess

**Comment by devshgraphicsprogramming** [comment]
But base has a public static function ?

**Comment by Crisspl** [comment]
Apparently it tries to access reserved_size through inheritance no matter what... Not sure if it's standard behavior but msvc does the  same. protected inheritance should do then. In this case at least

**Comment by devshgraphicsprogramming** [comment]
maybe if we use `typename` in front to make it access without inheritance?

**Comment by Crisspl** [comment]
>`include/irr/core/alloc/address_allocator_traits.h(139): the std::declval<U&>().template multi...` syntax really confused the compiler. Removing the `template` worked but I'm sure that's not the right fix.

Why actually removeing the `template` is not the right fix? IMHO it's ok. Also i see that `multi_alloc_addr` is not always template (`IAddressAllocator`) so i'm not sure what was intended meaning of this `template`. Anyway we don't need `template` keyword for calling a template function .

>maybe if we use typename in front to make it access without inheritance?

idk if this changes anything, but why not try..

**Comment by devshgraphicsprogramming** [comment]
Can you construct a unit test/example for the `address_allocator_traits` that it correctly reports whether the `address_allocator` actually has a `multi_alloc` and a `multi_free` method (templated or not) ?

The reason I had to put in that `template` in the first place was because the meta-function for non-template version was not catching the existence of the present forwarding template `multi_alloc` and `multi_free`

**Comment by devshgraphicsprogramming** [comment]
There's only 9 combinations of the multi_alloc+multi_free methods in an address allocator, its basically power of two of:
A. Not Present
B. Present but not templated
C. Templated forwarding

**Comment by devshgraphicsprogramming** [comment]
@Crisspl can you check that https://github.com/buildaworldnet/IrrlichtBAW/commit/e347ea7a25c3ca4b6a05e40383125ecf5c2b3b20 fixes the following issue

>include/irr/core/alloc/HeterogenousMemoryAddressAllocatorAdaptor.h(95): HeterogenousMemoryAddressAllocatorAdaptor inheriting AddressAllocator as private broke later in ResizableHeterogenousMemoryAllocator::multi_free_addr that expected to access AddressAllocator::reserved_size which was inaccessible. Changing to public inheritance fixed it.

**Comment by devshgraphicsprogramming** [comment]
Regarding the first problem on the list
```

	typedef irr::core::impl::address_allocator_traits_base<core::ContiguousPoolAddressAllocatorST<uint32_t>,true > trait_base;
	printf("Support %d\n",trait_base::maxMultiOps);
```

GCC ingests, compiles and runs this without issue in 01.HelloWorld, whats the situation like with MSVC?

**Comment by devshgraphicsprogramming** [comment]
Ok I've actually constructed the unit test for the allocator static type traits.

**Comment by devshgraphicsprogramming** [comment]
Fixed all of the problems, @Crisspl  can you test whether MSVC likes my code now?

**Comment by devshgraphicsprogramming** [comment]
Fixed with merge

**Comment by manhnt9** [comment]
I get

irr/core/alloc/address_allocator_traits.h:160:55: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
             _IRR_STATIC_INLINE_CONSTEXPR uint32_t     maxMultiOps                 = resolve_maxMultiOps<AddressAlloc>::value;

so we require C++17 now?

**Comment by devshgraphicsprogramming** [comment]
This issue is kind of hard to solve, without the `inline` it compiles but fails to link.

Maybe we should replace the constexpr with std::integral_constant and irr::bool_constant types instead

**Comment by manhnt9** [comment]
I tag #179 here so we won't forget about this warning.
