### ISSUE TITLE
CMake generation error

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#175]
### Error 1
Cannot find source file:
CGPUTransientBuffer.cpp

### Error 2
After commenting out CGPUTransientBuffer.cpp, errors with line 50 and 168 are printed out multiple times in single run.
```
CMake Error at CMakeLists.txt:50 (add_compile_options):
  Error evaluating generator expression:

    $<$CONFIG:DEBUG>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  source/Irrlicht/CMakeLists.txt:168 (irr_adjust_flags)
```

### Environment
Ubuntu 18.04
CMake v3.12.2

**Comment by devshgraphicsprogramming** [comment]
CGPUTransientBuffer.cpp is no longer around.

I believe I had these errors and it worked regardless @Crisspl ?

**Comment by Crisspl** [comment]
1. Cmake scripts just need to be updated more often while we're removing/adding sources
2. Yeah, that's known. Generally speaking it's correct that `$<$CONFIG:DEBUG>` should be evaluated to empty string or whatever which will cause cmake not to add this option in non-debug conf but idk why cmake prints those messages. It doesn't affect actual build at all though. Plus it happens on Linux only. Maybe try updating cmake

**Comment by manhnt9** [comment]
Seeing errors stops me from calling `make`, it's actually building the lib.
But I'm getting various `error: invalid use of incomplete type` output, try adding some #include now.

**Comment by manhnt9** [comment]
It builds after adding missing include to a .cpp file. But I notice that:
- Code::Blocks generates 8.8Mb lib, CMake makes it 10Mb
- Examples are not built although this build option is turned on

**Comment by manhnt9** [comment]
- Also need to add option to disable server lib
- Add install target to get fresh lib, include, examples, media without leaving them with generated build files (Makefile & CMake files and folders)

**Comment by Crisspl** [comment]
Build examples options causes cmake to generate makefiles for examples. You have to treat them separately with make though. I think so.. I'm not really familiar with `make`

**Comment by manhnt9** [comment]
I think if we enable examples in build option, it should build all examples. (And it's possible).
Or we can add more options to let user choose which examples to be included in build.

Or  separate examples completely from lib build and provide standalone CMake scripts for them so user can decide which one to build.
As @devshgraphicsprogramming said the project will provide Windows binaries, I suggested having another git repo for examples so we may need to decide this first before fixing examples' CMake.

**Comment by devshgraphicsprogramming** [comment]
I wouldn't have another repo for examples source code, I would have another git repo for BUILT examples + media files

**Comment by manhnt9** [comment]
../../src/irr/video/HostDeviceMirrorBufferAllocator.cpp
	../../src/irr/video/SimpleGPUBufferAllocator.cpp
these files aren't presented in repo but still in CMake (latest commit)

**Comment by devshgraphicsprogramming** [comment]
PR?

**Comment by manhnt9** [comment]
Soon, I'm debugging my reflection rays.

**Comment by Crisspl** [comment]
Oh, i guess i had a few commits old HEAD while updating CMakeLists

**Comment by devshgraphicsprogramming** [comment]
whats the status on this?

**Comment by manhnt9** [comment]
It is usable, but produce error warnings on Linux.

**Comment by devshgraphicsprogramming** [comment]
if its usable and no one has a PR to fix the spurious warnings I'm closing
