### ISSUE TITLE
Write a CEGUI example

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#176]
https://github.com/buildaworldnet/IrrlichtBAW/issues/27#issuecomment-438669875

**Comment by devshgraphicsprogramming** [comment]
we can disuss which OpenGL states to ignore and which to preserve here.

**Comment by manhnt9** [comment]
I will create this example on next weekend.

**Comment by manhnt9** [comment]
Well sorry I forgot about this issue, was too busy. I will solve when I work with CEGUI to write support for my renderer.

**Comment by devshgraphicsprogramming** [comment]
superseded by #254
