### ISSUE TITLE
Segfault with core::vector

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#185]
I'm using core::vector to store all my lines in a frame.
At the end of that frame, I draw the lines and clear the vector.
After the app is running for a short time (under 30sec), it crashes.
(latest commit)

My m_lines var is inaccessible (core::vector)
![screenshot_2018-11-19_10-36-41](https://user-images.githubusercontent.com/11463928/48685059-080f6700-ebe7-11e8-92f3-ce274cab93f9.png)

Call stack
![screenshot_2018-11-19_11-05-42](https://user-images.githubusercontent.com/11463928/48685840-21b2ad80-ebeb-11e8-8d55-16b31e73ac86.png)

My m_images is bloated (it only stores some albedo textures of the whole scene)
![screenshot_2018-11-19_10-37-55](https://user-images.githubusercontent.com/11463928/48685118-4c9b0280-ebe7-11e8-95f8-dba1ce0e6c65.png)

Re-run app to debug m_images

After the first push back, it's already bloated
![screenshot_2018-11-19_10-54-55](https://user-images.githubusercontent.com/11463928/48685583-9dabf600-ebe9-11e8-8362-263c768159bd.png)

Second push back makes it worse
![screenshot_2018-11-19_10-55-41](https://user-images.githubusercontent.com/11463928/48685609-b87e6a80-ebe9-11e8-93e7-8ace8fba74a6.png)

**Comment by devshgraphicsprogramming** [comment]
I doubt its a problem with core::vector as its basically nothing else other than a alias for std::vector with a custom allocator,you can actually try to make core::vector a straight forward alias for std::vector without customizing the allocator and you will get the same result/problem.

Probably your particular program had a problem with overwriting its own stack or other memory

**Comment by manhnt9** [comment]
Interesting about overwriting, my app is single-threaded. The only thing that I doubt is something becomes unstable under heavy usage. Will check more. Anyways, there has been some memory fixes recently, it may disappear. Close for now and will re-open later if needed.

**Comment by devshgraphicsprogramming** [comment]
All it takes is just too big stack arrays to be declared or your app to write past the end of its memory for the stack to be corrupted giving the segfaults in other places than they originate.
