### ISSUE TITLE
Disable the Annoying INSTALL, ZERO_CHECK and ALL_BUILD targets in CMake generated IDE projects.

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#194]
Title says it all.

I don't really care about ZERO_CHECK and ALL_BUILD as much as not having the confusing and annoying INSTALL target (IrrlichtBAW is for now a static lib, so installing to a location is pointless).

**Comment by devshgraphicsprogramming** [comment]
@Crisspl / @manhnt9  any ideas?

**Comment by Crisspl** [comment]
From what I've found:
* `BUILD_ALL` cannot be ommited
* `ZERO_CHECK` is kinda useful if you updated cmake scripts, however it can be forced to not be generated with `set(CMAKE_SUPPRESS_REGENERATION true)` in root CMakeLists.txt
https://stackoverflow.com/questions/27175754/what-are-all-build-and-zero-check-and-do-i-need-them
* idk about `INSTALL`

**Comment by manhnt9** [comment]
I would leave it as is since ZERO_CHECK will re-run CMake so Visual Studio users don't need to call it manually. These targets are only available for Visual Studio. Even install target makes sense to me, I'm using it to allow users to install headers, static lib, sample binary and media to a specific location.

**Comment by devshgraphicsprogramming** [comment]
Ok, we leave `BUILD_ALL` and `ZERO_CHECK`

But please remove `INSTALL`

**Comment by devshgraphicsprogramming** [comment]
https://stackoverflow.com/questions/13381742/cmake-exclude-executable-during-install/17202096#17202096

**Comment by devshgraphicsprogramming** [comment]
http://cmake.3232098.n2.nabble.com/Disabling-INSTALL-target-for-subdirectory-td7595059.html

**Comment by devshgraphicsprogramming** [comment]
https://stackoverflow.com/a/49081165/9951367

**Comment by devshgraphicsprogramming** [comment]
hmm nevermind, I actually found the install target quite useful at work
