### ISSUE TITLE
Examples and Tools CMake generated projects have wrong OpenSSL library paths 

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#195]
Irrlicht and IrrlichtServer targets build normally with no issues, its only the other stuff.

@Crisspl any comment?

**Comment by devshgraphicsprogramming** [comment]
looks like a file extension typo (double .lib)
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file '..\..\..\openssl\lib\libeay32.lib.lib'	hardwareinstancing	
```

**Comment by devshgraphicsprogramming** [comment]
@Crisspl actually without `_NASTY_OPENSSL_WORKAROUND_` (when I properly set the paths myself), everything builds nicely

So we can probably kill `_NASTY_OPENSSL_WORKAROUND_`, since it does more harm than good.

But the examples (nor does the `convert2BAW` tool) don't `INSTALL` or `ALL_BUILD` their executables to the correct directory.

@khom-khun maybe something you'd like to help to fix?

**Comment by devshgraphicsprogramming** [comment]
@manhnt9 beware of the examples not INSTALL'ing properly (when install path is set to `./lib/$PLATFORM` )

**Comment by manhnt9** [comment]
I'm not gonna use `make install` actually, will just compile, run and link to required files manually since I highly doubt that CMake code is ready for installing everything.

**Comment by devshgraphicsprogramming** [comment]
Actually @manhnt9 I use the INSTALL target on windows exclusively (as well as everyone at work) since I booted the MSVC projects from the repo.

CMake code is ready for INSTALLing everything, but the problem is it only installs the .lib/.a

**Comment by devshgraphicsprogramming** [comment]
@manhnt9 @Crisspl maybe we could get together and talk about whats the best solution for addressing this issue as well as #155 w.r.t. making the examples be built in sane locations, figuring how to make this configuration header install nicely and how to install the built binaries nicely, making the code of the examples work from both these out-of-source locations and install locations. Or alternatively not have the examples install at all, because right now, thinking of it... it kind-of makes no sense.

I would really value @manhnt9 's perspective as a seasoned and avid CMake user.

**Comment by Crisspl** [comment]
As for now i changed output dir of examples/tools to where they were outputted before CMake. And got rid of `NASTY_OPENSSL_WORKAROUND` so this issue can be marked as resolved actually. However making IrrCompileConfig.h into CMake options is whole new subject so yea we could talk about this and other things you mentioned.

**Comment by devshgraphicsprogramming** [comment]
Ok closing, installing headers and configure header should be a whole other issue.
