### ISSUE TITLE
Get rid of CColorConverter

### ISSUE THREAD

**Issue by Crisspl** [buildaworldnet/IrrlichtBAW#208]
Replace all of its use cases in engine with new `convertColor` functions

**Comment by devshgraphicsprogramming** [comment]
Depends #148

**Comment by devshgraphicsprogramming** [comment]
See https://github.com/buildaworldnet/IrrlichtBAW/pull/273#commitcomment-33615162

**Comment by devshgraphicsprogramming** [comment]
After cleanup branch is complete only BMP loader and writer will use it

at this point @Przemog1 feel free to take over
