### ISSUE TITLE
Map PVRTC GL enum onto E_FORMAT

### ISSUE THREAD

**Issue by Crisspl** [buildaworldnet/IrrlichtBAW#210]
Since E_FORMAT is actually copy-paste of VkFormat: https://github.com/KhronosGroup/Vulkan-Docs/issues/512

Also: i'm not sure whether we should have formats from [EXT_pvrtc_sRGB](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_pvrtc_sRGB.txt) and [IMG_texture_compression_pvrtc2](https://www.khronos.org/registry/OpenGL/extensions/IMG/IMG_texture_compression_pvrtc2.txt) in engine since those extensions are written agains OpenGL ES. So is [GL_IMG_texture_compression_pvrtc](https://www.khronos.org/registry/OpenGL/extensions/IMG/IMG_texture_compression_pvrtc.txt), but it's also pointed out that GL ES 1.0 is derived from desktop GL 1.3.

**Comment by devshgraphicsprogramming** [comment]
I think you should just not worry and mark these formats as not supported in the OpenGL  video driver.

So no E_FORMAT to GL_enum needed.

PVRT is a format for iOS and OS X, and that will only be supported on Vulkan with Molten VK
