### ISSUE TITLE
Master does not compile on GCC

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#225]
A bigger issue encompassing #224

**Comment by devshgraphicsprogramming** [comment]
Builds in release and debug mode under code::blocks + Unix Makefiles, closing

**Comment by devshgraphicsprogramming** [comment]
@Crisspl I do however absolutely drown in warnings when compiling the Debug release.

The output of the compiler to stdout is whats making the compilation slow!

Can we do anything about the `-Wswitch` emitted by the E_FORMAT includes?

**Comment by devshgraphicsprogramming** [comment]
Also if we can add `-Wno-ignored-attributes` to the compiler options for GCC for both debug and release, it would be great.

**Comment by devshgraphicsprogramming** [comment]
See https://github.com/buildaworldnet/IrrlichtBAW/issues/179#issuecomment-466755106

**Comment by Crisspl** [comment]
https://gcc.gnu.org/onlinedocs/gcc-4.8.2/gcc/Warning-Options.html

>-Wswitch
Warn whenever a switch statement has an index of enumerated type and lacks a case for one or more of the named codes of that enumeration. (The presence of a default label prevents this warning.)

Hm seems like just a `default:` should do the job, however I see just two switches in `EFormat.h` that haven't got `default:` (none in decode, encode nor convert headers). I know that `EFormat.h` is included in many places and any error in there multiplies dramatically but 100k??? Is it the only file that produces such amounts of `-Wswitch`es?

**Comment by devshgraphicsprogramming** [comment]
100k is the overall number of warnings when building. I think we should move this discussion to #179
