### ISSUE TITLE
Implement Gamma Correct Rendering

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#234]
`HandleSRGB` from creation parameters should disappear (assume always true).
https://github.com/buildaworldnet/IrrlichtBAW/pull/252#commitcomment-32961321

This should be uncommented in COpenGLDriver.cpp
```c++
	if (Params.HandleSRGB)
		glEnable(GL_FRAMEBUFFER_SRGB);
```

And finally all texture loaders should be validated to load all formats correctly (need a unit-test/example for that).

**Comment by devshgraphicsprogramming** [comment]
This is a good occasion to tackle other Texture-API-related issues

**Comment by devshgraphicsprogramming** [comment]
Only a few lines of code need to be changed in CImageLoader* for different LDR formats
https://github.com/buildaworldnet/IrrlichtBAW/tree/master/src/irr/asset

But needs thorough testing with real images (load image, make it into texture, copy/blit it onto the screen and compare with Windows/Linux Photo viewer).

**Comment by devshgraphicsprogramming** [comment]
Maybe https://github.com/buildaworldnet/IrrlichtBAW/blob/master/src/irr/asset/CImageLoaderRGB.cpp image loader can be removed (killed)

**Comment by devshgraphicsprogramming** [comment]
Image writers also need to be adjusted to correctly save textures (respect SRGB, and for non SRGB do colorformat conversion, **for which we already have functions** ).

**Comment by Crisspl** [comment]
Allow only RGB color space and report error on others (return nullptr)

**Comment by devshgraphicsprogramming** [comment]
linear RGB and sRGB

**Comment by devshgraphicsprogramming** [comment]
A basic TODO list:
- [x] Remove `HandleSRGB` window creation parameter (assume always true)
- [x] Remove the RGB image loader
- [x] Provide extra GLenum conversions https://github.com/buildaworldnet/IrrlichtBAW/pull/250#discussion_r271620010
- [x] Fix up the Image Loaders
- [x] Create a Unit Test with multiple images being tested 
- [x] Display Image on screen with full-screen triangle (blit not allowed)
- [x] Fix up the Image Writers
- [x] Create a Screenshot of the image on the screen and save to file
- [ ] Provide a static SColorf

List of Texture Formats to Test
- [x] JPEG color
- [x] JPEG grayscale
- [x] PNG 8bit grayscale
- [x] PNG 24bit rgb
- [ ] PNG 32bit rgba
- [x] TGA without transparency
- [ ] TGA with transparency
- [x] Basic BMP
- [ ] Extended BMP with gamma or ICC information
- [ ] DDS in all non-compressed formats
- [ ] DDS in all DXTn compressed formats

The images must look 99% the same color-wise when displayed on screen and written to file
**NOTE 1: We don't have DDS,BMP writers, so don't test writing to file for those formats!** 
**NOTE 2:** Do not add random images to the media folder if you don't know the license for them (plus many PNG formats can be found in the sponza scene).

P.S. Can remove TGA writer if its not easy enough to fix.

**Comment by devshgraphicsprogramming** [comment]
This is my new branch that sRGB work should be based on/merged into

https://github.com/buildaworldnet/IrrlichtBAW/tree/sRGB

**Comment by devshgraphicsprogramming** [comment]
@manhnt9 you guys will need to implement loading JPEGs with the JCS_GRAYSCALE colorspace.

**Comment by manhnt9** [comment]
CC: @Florastamine
This is the first step in the task.

**Comment by devshgraphicsprogramming** [comment]
I'm doing a small change that will support YCbCr

**Comment by manhnt9** [comment]
OK, maybe we can start our task next week.

**Comment by devshgraphicsprogramming** [comment]
@manhnt9 @Florastamine unit test outline done, its number 9

**Comment by devshgraphicsprogramming** [comment]
> NOTE 1: We don't have DDS,BMP writers, so don't test writing to file for those formats!

basically when loading DDS/BMP the output file needs to be PNG and the output file format needs adjusting accordingly
also the CPU2CPU roundtrip (load asset, write asset) obviously cannot be done, so disable testing that for the DDS and BMP

**Comment by devshgraphicsprogramming** [comment]
@Florastamine refer to this when reworking the image writers (make sure they always have a default case switch when handling formats)

https://github.com/buildaworldnet/IrrlichtBAW/issues/144#issuecomment-486803600

**Comment by devshgraphicsprogramming** [comment]
One last thing to do is to provide a static member function for SColorf called `fromSRGB` that will construct a linear RGBA color from SRGB_ALPHA values
