### ISSUE TITLE
BRDF Explorer GUI

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#254]
We can discuss and update progress on GUI development of BRDF Explorer extension here.

Developer: @Florastamine
Adviser: @manhnt9 @devshgraphicsprogramming 

Screenshots: to be updated when there's new progress from @Florastamine

Notes after discussion on Discord:
- Enable sRGB textures in CEGUI
- Color Picker: CEGUI's class, add color wheel if possible (low priority)
- File dialog: nativefiledialog library
- Theme: TaharezLook or AlfiskoSkin

Task list made by @Florastamine:

- [x] Remove the loaded resource paths list box
- [x] Change light & material parameters into sliders
- [x] Review slider ranges
- [x] Fix roughness sliders & add a lock checkbox
- [x] Make the AO & bumpmapping thumbnail click-able
- [x] Add an option to select between tweakable shader constants or from texture
- [x] Improve the texture preview window
- [x] Transparent panels & make the GUI optionally toggle-able
- [x] Replace WindowsLook theme with a better fit one (preferably dark, blue-ish)

How to integrate CEGUI into IrrBAW:
- Study [Example 33](https://github.com/buildaworldnet/IrrlichtBAW/tree/master/examples_tests/33.Draw3DLine) to understand extension architecture
- Write a CEGUI manager class as extension
- Fork IrrBAW, checkout branch stable-ish
- Create another IrrBAW example for BRDR Explorer

How to render CEGUI with IrrBAW:
Use this code snippet for GUI rendering
```cpp
auto renderState = irr::video::COpenGLState::collectGLState();
irr::video::COpenGLState guiState;
executeGLDiff(guiState.getStateDiff(renderState));  
CEGUI::System::getSingleton().renderAllGUIContexts();
executeGLDiff(renderState.getStateDiff(irr::video::COpenGLState::collectGLState()));
```
See more about how to use IrrBAW's OpenGL state manager at this [file](https://github.com/buildaworldnet/IrrlichtBAW/blob/stable-ish/examples_tests/13.Silverlining/main.cpp#L769).

Notes:
- Only use stable-ish branch, will try to merge in to unstable master later (need DevSH's advices)
- Commit with CEGUI datafiles (filter out what is used)

**Comment by devshgraphicsprogramming** [comment]
This is my provisional and not yet complete list of CEGUI themes I find attractive:
- https://sourceforge.net/projects/glossyserpent/ (last resort)
- Whats the theme that "CEGUIGameMenuDemo" uses?
- Taharez Look (its dark)

Btw, what does CEGUI use for font rendering?

**Comment by devshgraphicsprogramming** [comment]
I think you're missing a drop-down list for the BRDF models, which are outlined in the PDF spec of the BRDF Explorer (I think there are about 5 or so).

> Change roughness/metallic/refraction spinners into sliders

I personally think that sliders would be good for colors as well ( in addition to color picker), but if that is impossible for some reason, let me know.

![image](https://user-images.githubusercontent.com/6894321/55671614-2a520a80-5892-11e9-9430-bb982fff17a1.png)
I would make it so that when the image slot preview (in the resource dock window) is clicked on, the file dialog is opened instead of the current set-up.

Remember that the BRDF explorer states the following:
> Give the User a choice whether values should come from textures or be ”constants”
tweakable with GUI sliders

(can use a dropdown list with 5 options, "Constant", "Texture 0", "Texture 1", ...)
(you can show the texture preview when its a texture, and 4 sliders when its a constant)

> Textures are bound to channels, channels can be bound to shader parameter inputs. No textures directly to inputs, shader input can only choose texture channel.

![image](https://user-images.githubusercontent.com/6894321/55671640-9af92700-5892-11e9-93c3-36fcd60792ac.png)
Light position can stay as a spinner.

The roughness value will need two sliders, and its a bit complicated:
> a ”lock” checkbox that makes two roughness sliders locked together so both produce
the same value (grey it out when isotropic [note: only anisotropic BRDF is Ashkimin Shirley] BRDFs are used).

**The bumpmap height/scale parameter is the only one that does not have a 0-1 range, it needs a bit extra range (like 1-20 or something like that).**

P.S. I know I'm being picky, so forgive me for this comment
![image](https://user-images.githubusercontent.com/6894321/55671825-4eaee680-5894-11e9-82e6-e7b8d4c4e0ae.png)
I think the texture buttons should be arranged into a 2x2 quad like in Shader Maker

**Comment by manhnt9** [comment]
The CEGUI GameGUI demo uses something else (it's own theme), we can try that.
CEGUI uses FreeType for font rendering.
And this is TaharezLook. ![](http://i.imgur.com/AzzwgTJ.png)

**Comment by devshgraphicsprogramming** [comment]
Looks like a perfectly acceptable skin for the final product.

**Comment by manhnt9** [comment]
You mean TaharezLook or GameMenu theme?

**Comment by devshgraphicsprogramming** [comment]
@manhnt9 asked for a list of BRDF/BSDFs (I presume for the drop-down lists).

Specular:
- GGX Plastic&Conductor Mix
- Ashikhmin-Shirley Plastic&Conductor Mix (that one needs the coupled roughness sliders to be "freed" to be independent)
- Perfect Dielectric (disables diffuse)
- GGX Rough Dielectric (disables diffuse)
- Thin Dielectric (disables diffuse)

Diffuse:
- Orren-Nayar
- Lambert
- Disabled (nice to display when greyed out)

Note: Who's to implement those is yet to be decided (its a separate issue on its own).

**Comment by manhnt9** [comment]
Should it be check boxes instead? So viewer can see combined models, maybe?

**Comment by devshgraphicsprogramming** [comment]
No, you pick one BRDF for diffuse and another for specular, there are no other combinations that make sense.

**Comment by manhnt9** [comment]
OK, so there'll be 2 dropdown lists. I was thinking about the break-down of the components for a fixed BRDF algorithm. So we'll have multiple ways of calculate the effects and visualize the final BRDR render, so the dropdown is like graphics setting. Interesting! I should learn these.

**Comment by devshgraphicsprogramming** [comment]
Diffuse and Specular are orthogonal to each other, one is short range scattering the other is reflection.

**Comment by manhnt9** [comment]
I've found papers of Lambert, Oren-Nayar, GGX, Ashikhmin-Shirley. Where do I learn about these below?
- GGX Plastic&Conductor Mix (how to apply GGX to have it)
- GGX Rough Dielectric
- Perfect Dielectric 
- Thin Dielectric

**Comment by devshgraphicsprogramming** [comment]
GGX Metallic workflow:
https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf

The Dielectrics I'll do myself.

**Comment by manhnt9** [comment]
Update about theme choice:
- TaharezLook
- Or AlfiskoSkin

**Comment by ghost** [comment]
Current progress. The color picker is now available, along with a complete layout overhaul.
![](https://i.imgur.com/WymrAPu.jpg)

The currently used theme is a variant of AlfiskoSkin with custom modifications & additional widgets ported from the vanilla CEGUI skin. I tried sticking to imgui's default color scheme
![](https://i.imgur.com/gzou4nd.png)

For reference, here's the original AlfiskoSkin:
![](https://i.imgur.com/wvuHLjV.png)

Checking the checkbox (heh!) will now lock one slider & enforce two sliders to be equal:
![](https://i.imgur.com/NPCfVUQ.png)

A drop-down list is now available and will disable GUI sliders if "Constant" is selected:
![](https://i.imgur.com/eiAP6NU.png)

**Comment by Crisspl** [comment]
>I've found papers of Lambert, Oren-Nayar, GGX, Ashikhmin-Shirley.

@manhnt9 Can you post the links here?

**Comment by manhnt9** [comment]
@Crisspl I downloaded and didn't save the links. Give me your email address, I will send.

**Comment by Crisspl** [comment]
Send to the one assigned to my GitHub account (viewable in profile page), thanks :)

**Comment by devshgraphicsprogramming** [comment]
> @manhnt9 Can you post the links here?

Guys I made the bibliography in the Overleaf PDF for a reason, you can retrieve most references as links anyway.

**Comment by devshgraphicsprogramming** [comment]
@Florastamine can you give me the GUI prototype to play with?

Beautiful work.

I don't currently understand how you've done the whole "source" drop down.

**Comment by devshgraphicsprogramming** [comment]
@Florastamine its the "Roughness" that can be anisotropic, **not** the Refraction Index

**Comment by manhnt9** [comment]
I think @Florastamine can send a binary version for Matt to play with it. It's time to tune to GUI features. Visual is good now I think. Do you prefer Windows or Linux version?

**Comment by devshgraphicsprogramming** [comment]
Whatever is easiest for you.

**Comment by ghost** [comment]
@devshgraphicsprogramming Yes, I have just corrected that now. Sending binaries your way

**Comment by devshgraphicsprogramming** [comment]
> Light position can stay as a spinner.

Should be a numerical value per each XYZ coordinate that can be typed

**Comment by manhnt9** [comment]
@devshgraphicsprogramming Could you make an issue specifying what do you need for CEGUI sRGB texture and color picker?

**Comment by devshgraphicsprogramming** [comment]
open one and write down your questions, also give me links to CEGUI source files as reference ;)

**Comment by ghost** [comment]
I have updated the GUI to reflect necessary changes, please download included binaries (Windows-only) & test them well.

[BRDFExplorerGUI.zip](https://github.com/buildaworldnet/IrrlichtBAW/files/3097978/BRDFExplorerGUI.zip)

![](https://user-images.githubusercontent.com/4599467/56422777-63976b00-62d3-11e9-8c66-25b901083e19.png)

**Comment by devshgraphicsprogramming** [comment]
I'm missing libgcc.dll and libfreetype.dll etc., could you possibly make a statically linked build?

**Comment by ghost** [comment]
I hope I've got all possible dependencies sorted out... it's so monstrosity that making a statically build is a huge feat.

[BRDFExplorerGUI.zip](https://file.io/d9a1aM)

It's bloated, but should run on anything. Just Windows things, I guess.

**Comment by manhnt9** [comment]
I'm missing: libCEGUIExpatParser.dll

**Comment by ghost** [comment]
Updated.

**Comment by manhnt9** [comment]
Nice, it even runs on Linux with Wine.

![Screenshot_2019-04-20_18-04-54](https://user-images.githubusercontent.com/11463928/56456452-e03f4d80-6396-11e9-8d22-f849e2d56026.png)

**Comment by ghost** [comment]
A bug which made certain UI elements impossible to click through has been fixed, new files were issued.

**Comment by devshgraphicsprogramming** [comment]
> A bug which made certain UI elements impossible to click through has been fixed, new files were issued. Please download it here.

I think at this point a public git repo is in order ;)

**Comment by manhnt9** [comment]
We will publish the source and merge into irrbaw when the GUI part is marked as done. Then we concentrate on the BRDF part and GUI should be touched as little as possible. It helps us to assure the overall integrity.

**Comment by devshgraphicsprogramming** [comment]
btw @Florastamine I can no longer download the zip

**Comment by ghost** [comment]
@devshgraphicsprogramming I've updated the expiration date to a maximum of 1 week. Please try to download the file again.

[BRDFExplorerGUI.zip](https://file.io/d9a1aM)

**Comment by devshgraphicsprogramming** [comment]
I still get a 404

**Comment by ghost** [comment]
[BRDFExplorerGUI.zip](https://github.com/buildaworldnet/IrrlichtBAW/files/3108835/BRDFExplorerGUI.zip)

**Comment by devshgraphicsprogramming** [comment]
Ok my comments from testing:
- The example app doesn't like my dual monitor set-up, everything is scaled down badly and not very legible (usually not a problem, as integration will be into irrBAW)
- The 2x2 grid of textures is not clickable (no file load dialog from click)
- not all GUI gets hidden by F1
- its possible to crash the color picker by clicking on its window titlebar repeately
- when isotropic roughness is set, the background of the fader fails to update
- MapHeight is an integer slider, should allow for fractions between 0 and 1 as well
- The Color Picker Preview and "Choose Color ..." GUI elements should not blend against the background (the viewed colours are wrong when blending the color previous against the background)

If you address the above then I believe we're done on the GUI design front.

**Comment by ghost** [comment]
> The example app doesn't like my dual monitor set-up, everything is scaled down badly and not very legible (usually not a problem, as integration will be into irrBAW)

It'd be nice if you could provide a screenshot & your resolution. I personally don't have a lot of resources to test against every single resolution & monitor setup, but I'll see what I can do. Could also be the GUI that is faulty.

> not all GUI gets hidden by F1

Do you mean this particular sliders window? It's something I put in just for the demo to easily set background colors, i. e. for testing purposes.
![image](https://user-images.githubusercontent.com/4599467/56725687-887a5b00-6777-11e9-9426-33a7b9cad36e.png)

The rest should be trivial to fix.

**Comment by ghost** [comment]
A new build is now live.
![image](https://user-images.githubusercontent.com/4599467/56845990-69083d00-68f3-11e9-9105-bbd6d59ce116.png)

Apart from the fixes, the text fields in both AO & bump-mapping window now accept manual input & would pop out an error message if the file couldn't be found.
![image](https://user-images.githubusercontent.com/4599467/56846004-91903700-68f3-11e9-9fae-4367bbf3aa66.png)

The texture preview window was also improved to display its child textures' name.
![image](https://user-images.githubusercontent.com/4599467/56846042-25620300-68f4-11e9-9da0-0d5abd1d228a.png)

There are two known issues remain, both of which is CEGUI's: [Crash on double-clicking the ColourPicker's titlebar](https://bitbucket.org/cegui/cegui/issues/1165/crash-on-double-clicking-the-colourpickers), [CEGUI::ColourPickerControls doesn't respect CEGUI::ColourPicker::setVisible()](https://bitbucket.org/cegui/cegui/issues/1166/cegui-colourpickercontrols-doesnt-respect).

[BRDFExplorerGUI.zip](https://github.com/buildaworldnet/IrrlichtBAW/files/3123689/BRDFExplorerGUI.zip)

**Comment by devshgraphicsprogramming** [comment]
lovely

**Comment by devshgraphicsprogramming** [comment]
Minimal issues:
- Native file dialog starts off with `*.bmp` mask so when I browse my folders I can't see jpegs and pngs all at once, maybe start with `.*`
- The FPS is rather low (only 30 FPS) , I don't need it fixed I just need to know why
- The background behind sliders (the slider gradient has issues updating)
![image](https://user-images.githubusercontent.com/6894321/56849308-175fb280-68f3-11e9-8c06-f0f7bfa1a5ab.png)

P.S. It's sad that the rounded corners have had to be sacrificed, but those buttons could be made a bit smaller (now they feel feally big compared to everything else.

**Comment by ghost** [comment]
New build here: [BRDFExplorerGUI.zip](https://github.com/buildaworldnet/IrrlichtBAW/files/3124021/BRDFExplorerGUI.zip)

> The FPS is rather low (only 30 FPS)

Weird. I got 60 with V-Sync and 5,000 uncapped.

> The background behind sliders (the slider gradient has issues updating)

There's nothing I could do about that I'm afraid. For reference, the original Alfisko also exhibits the same inconsistent behavior when it comes to updating the sliders:
![image](https://user-images.githubusercontent.com/4599467/56851576-d25f6e80-693a-11e9-81e7-c48b409a4b4c.png)

It pretty much happens at random and the only way to get the sliders updated correctly is to drag another slider, but then the dragged one is also affected. I really have no clue if it's CEGUI being iffy or the theme itself. Might as well investigate later.

The file dialog issue has been fixed. Additionally, tooltips have been implemented for certain widgets (the texture buttons, for example, which can show additional information, i. e. size, date/time, etc. when hovering on them):
![image](https://user-images.githubusercontent.com/4599467/56851639-7fd28200-693b-11e9-8f53-377fba6fc247.png)

**Comment by manhnt9** [comment]
I have 50-60 FPS and 5000 max on Linux with Wine.

**Comment by devshgraphicsprogramming** [comment]
>
>
> There's nothing I could do about that I'm afraid. For reference, the original Alfisko also exhibits the same inconsistent behavior when it comes to updating the sliders:
image
It pretty much happens at random and the only way to get the sliders updated correctly is to drag another slider, but then the dragged one is also affected. I really have no clue if it's CEGUI being iffy or the theme itself. 

File an issue.

ok, we're done here then, lets dump the source to this somewhere and begin making example `13.BRDFExplorer`

**Comment by manhnt9** [comment]
Okay, I'll do a quick source code review and integrate into the example in this repo.

**Comment by ghost** [comment]
Three known (non-blocking) bugs remaining:
* [Crash on double-clicking the ColourPicker's titlebar](https://bitbucket.org/cegui/cegui/issues/1165/crash-on-double-clicking-the-colourpickers)
* [CEGUI::ColourPickerControls doesn't respect CEGUI::ColourPicker::setVisible()](https://bitbucket.org/cegui/cegui/issues/1166/cegui-colourpickercontrols-doesnt-respect)
* [AlfiskoSkin does not correctly update sliders' background](https://bitbucket.org/cegui/cegui/issues/1169/alfiskoskin-does-not-correctly-update)

Although given the authors' stance on various unsolved issues over the years (lack of manpower and such), we'd most likely have to fix them ourshelves somewhere down the line.

**Comment by manhnt9** [comment]
Yes, my plans also include CEGUI development so there'll be at least 1 person who helps fighting CEGUI issues in near future.
