### ISSUE TITLE
Linking to OpenSSL

### ISSUE THREAD

**Issue by Crisspl** [buildaworldnet/IrrlichtBAW#256]
@manhnt9 maybe you could help? Here's my question on SO describing current situation: https://stackoverflow.com/questions/55575025/linking-to-openssl-64-bit-static-library

I would be grateful if you'd recursivery clone my master (`git clone --recurse-submodules ...`), generate VS files with cmake, try to build it (preferably on Release config because Release openssl is being built) and see if the same happens. Maybe a fresh look can notice something I haven't...

**Comment by manhnt9** [comment]
I can assign this to my intern in this week, he has been practicing modern CMake based on my instructions recently and had a really nice project for that. He can report and discuss with me so I will help. Sorry that I don't use or maintain my Windows version often enough.

**Comment by Crisspl** [comment]
Thanks, but nvm - solved finally :)
