### ISSUE TITLE
Build error on sRGB branch

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#264]
Git module needs a little fix I think

Scanning dependencies of target shaderc_combined_genfile
make[2]: *** No rule to make target '3rdparty/shaderc/libshaderc/libshaderc_combined.a', needed by '3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile'.  Stop.
CMakeFiles/Makefile2:3786: recipe for target '3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile.dir/all' failed
make[1]: *** [3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by Crisspl** [comment]
Build system on Linux is currently untested. However about this particular error: updating shaderc to the newest codebase should help. Most likely it concerns this issue https://github.com/google/shaderc/issues/568

**Comment by manhnt9** [comment]
I tried pulling shaderc, it's already the latest commit.

**Comment by manhnt9** [comment]
`touch 3rdparty/shaderc/libshaderc/libshaderc_combined.a` in build folder solves this issue.
But I have

[ 19%] Generating pch.h.gch/.c++
c++: error: PNG_THREAD_UNSAFE_OK: No such file or directory
c++: error: PNG_NO_MMX_CODE: No such file or directory
c++: error: PNG_NO_MNG_FEATURES: No such file or directory
c++: error: _7ZIP_ST: No such file or directory
c++: error: SPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS: No such file or directory
c++: error: IRRLICHT_FAST_MATH: No such file or directory

How to disable PCH? I think this should be optional.

**Comment by manhnt9** [comment]
Also I meet OpenSSL errors

[ 21%] Built target genfiles
[ 21%] Building OpenSSL...
make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: *** No targets specified and no makefile found.  Stop.
3rdparty/openssl/CMakeFiles/openssl_build.dir/build.make:61: recipe for target '3rdparty/openssl/build/lib/libcrypto.a' failed
make[2]: *** [3rdparty/openssl/build/lib/libcrypto.a] Error 2
CMakeFiles/Makefile2:4054: recipe for target '3rdparty/openssl/CMakeFiles/openssl_build.dir/all' failed
make[1]: *** [3rdparty/openssl/CMakeFiles/openssl_build.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 21%] Built target extinst_tables
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by devshgraphicsprogramming** [comment]
@manhnt9 my OpenSSL CMAKE linux path is untested, probably needs a fix-up

> How to disable PCH? I think this should be optional.

About PCH, I really want PCH so we should make it work (cuts down compile time in Debug builds).

**Comment by manhnt9** [comment]
This is incorrect approach in your CMake code.

```
option(SPIRV_HEADERS_SKIP_EXAMPLES "SPIRV-Headers examples" ON)
add_subdirectory(SPIRV-Headers)
option(SKIP_SPIRV_TOOLS_INSTALL "SPIRV-Tools install skip" ON)
option(SPIRV_SKIP_TESTS "SPIRV-Tools tests skip" ON)
```

These lines is declaring new options, not setting options for subdir project.
As a result, CMake tried to build SPIRV tests on my system and failed without GoogleMock.

**Comment by manhnt9** [comment]
Fixed that error. Now fixing OpenSSL build.

**Comment by manhnt9** [comment]
Blocker: https://github.com/nemtrif/utfcpp/issues/35

UtfCpp requires exceptions. Either we wait for it to be patched or enable exception in irrbaw.

[ 68%] Building CXX object source/Irrlicht/CMakeFiles/IrrlichtServer.dir/coreutil.cpp.o
In file included from /home/manh/IrrlichtBAW/3rdparty/utfcpp/source/utf8.h:31:0,
                 from /home/manh/IrrlichtBAW/source/Irrlicht/coreutil.cpp:2:
/home/manh/IrrlichtBAW/3rdparty/utfcpp/source/utf8/checked.h: In instantiation of ‘octet_iterator utf8::append(utf8::uint32_t, octet_iterator) [with octet_iterator = std::back_insert_iterator<std::__cxx11::basic_string<char> >; utf8::uint32_t = unsigned int]’:
/home/manh/IrrlichtBAW/3rdparty/utfcpp/source/utf8/checked.h:110:40:   required from ‘output_iterator utf8::replace_invalid(octet_iterator, octet_iterator, output_iterator, utf8::uint32_t) [with octet_iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; output_iterator = std::back_insert_iterator<std::__cxx11::basic_string<char> >; utf8::uint32_t = unsigned int]’
/home/manh/IrrlichtBAW/source/Irrlicht/coreutil.cpp:74:109:   required from here
/home/manh/IrrlichtBAW/3rdparty/utfcpp/source/utf8/checked.h:76:40: error: exception handling disabled, use -fexceptions to enable
             throw invalid_code_point(cp);
                                        ^
source/Irrlicht/CMakeFiles/IrrlichtServer.dir/build.make:1232: recipe for target 'source/Irrlicht/CMakeFiles/IrrlichtServer.dir/coreutil.cpp.o' failed
make[2]: *** [source/Irrlicht/CMakeFiles/IrrlichtServer.dir/coreutil.cpp.o] Error 1
CMakeFiles/Makefile2:2809: recipe for target 'source/Irrlicht/CMakeFiles/IrrlichtServer.dir/all' failed
make[1]: *** [source/Irrlicht/CMakeFiles/IrrlichtServer.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by manhnt9** [comment]
Temporary solution is to enable exceptions for dealing with other build issues.

**Comment by manhnt9** [comment]
Since we're using Git submodules, the following CMake code for OpenSSL is pointless.
You can and should use submodule to control the version of OpenSSL you use.
```
find_package(Git )

if (GIT_FOUND)
	# run those sequentially
	execute_process(COMMAND "${GIT_EXECUTABLE} fetch"
			WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/openssl"
	)
	execute_process(COMMAND "${GIT_EXECUTABLE} clean -fd"
		WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/openssl"
	)
	execute_process(COMMAND "${GIT_EXECUTABLE} reset --hard origin/OpenSSL_1_0_2-stable"
		WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/openssl"
	)
else()
	message(WARNING "Git not found! Might be you have to update git-submodules manually")
endif()
# maybe you (Crisspl) can patch the OpenSSL source for the preprocessor MSVC bug here?
```

**Comment by devshgraphicsprogramming** [comment]
> These lines is declaring new options, not setting options for subdir project.
As a result, CMake tried to build SPIRV tests on my system and failed without GoogleMock.

Works on Windows, I think windows needs `option` and Linux needs `set`... there's no harm in setting both. The subdirs set their options via `option` not `set` .

> Temporary solution is to enable exceptions for dealing with other build issues.

I've had this solved before moving to CMake, there are two files `checked.h` and `unchecked.h` one gives an implementation with and the other without exceptions

https://github.com/nemtrif/utfcpp/tree/master/source/utf8

**Comment by manhnt9** [comment]
About `option` and `set`, I think we should follow the standard. It doesn't have significant difference for now, but in future maybe. Normally `option` is to declare option for that project. It makes more sense to use set before adding subdir than to misunderstood those as new options.

About the exception, so we should use unchecked.h instead? Will try to see if it works.

**Comment by manhnt9** [comment]
`unchecked` doesn't have `find_invalid` and `replace_invalid`, which used in irrbaw's `UTF8StringToWString` and `UTF8StringToWString`

**Comment by devshgraphicsprogramming** [comment]
> It makes more sense to use set before adding subdir than to misunderstood those as new options.

Ok, but why the `FORCE` ?

> About the exception, so we should use unchecked.h instead? Will try to see if it works.

Yes, but this is about the file that gets included, not any CMake option really.

> Since we're using Git submodules, the following CMake code for OpenSSL is pointless.
You can and should use submodule to control the version of OpenSSL you use.

This is actually more complicated, that git code was there to clean and reset the submodule, not to control the version (I should really have done it so it resets to the head of the current branch).

We need to clean and reset when configuring beause OpenSSL doesn't support out-of-source builds, which means it pollutes the submodule folder.

**Comment by manhnt9** [comment]
Using FORCE so CMake overwrite current settings and people don't need to clear build folder and run CMake again. A minor issue though.

Reverting the git resetting part.

**Comment by devshgraphicsprogramming** [comment]
> Using FORCE so CMake overwrite current settings and people don't need to clear build folder and run CMake again. A minor issue though.

Wouldn't that overrride the setting if someone manually enables it for some reason?

**Comment by manhnt9** [comment]
Yeah, that also counts. But do you think one would test those deps in irrbaw repo directly? I would clone a new repo instead for not polluting my submodules. If you want to remove `FORCE`, confirm after this comment then I'll do.

**Comment by devshgraphicsprogramming** [comment]
> `unchecked` doesn't have `find_invalid` and `replace_invalid`, which used in irrbaw's `UTF8StringToWString` and `UTF8StringToWString`

`unchecked` includes `core` which defines `find_invalid`

**Comment by devshgraphicsprogramming** [comment]
> 
> 
> Yeah, that also counts. But do you think one would test those deps in irrbaw repo directly? I would clone a new repo instead for not polluting my submodules. If you want to remove `FORCE`, confirm after this comment then I'll do.

Well we should provide reasonable defaults but not override the settings all the time

**Comment by manhnt9** [comment]
I find no `replace_invalid` definition in `core.h`.

Removing the `FORCE`.

**Comment by manhnt9** [comment]
There's only the exception part left for the PR to merge I think.

**Comment by devshgraphicsprogramming** [comment]
> I find no replace_invalid definition in core.h. 

Yeah thats probably a thing we need to take up in the issue on the repo or provide a patch

**Comment by ghost** [comment]
Slightly related: CEGUI also utilizes exceptions (both internal & public API-wide) & would throw on errors. [They don't have a way (neither CMake nor `#define`) to override them without making changes to the source](http://cegui.org.uk/forum/viewtopic.php?t=3600). Only patching the throw macro `CEGUI_THROW()` to do nothing helps. Something we should also consider.

**Comment by devshgraphicsprogramming** [comment]
Well because CEGUI is not irrBAW core (only an extension), its okay for it to throw, because `-fexceptions` will only be a compile flag for the Examples that use CEGUI

**Comment by devshgraphicsprogramming** [comment]
Ok closing this as this seems fixed (bar the small exception throwing from utf8cpp).

@manhnt9, we should watch that issue or provide a non-throw `replace_invalid` patch to the repo.

**Comment by devshgraphicsprogramming** [comment]
Updated submodule and replaced the checked with unchecked
