### ISSUE TITLE
Complete a Wiki with Tutorials, Tips&Hacks and Peculiar Engine Behaviour

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#27]
Explain the tutorials more in depth.

Some general GPU Programming Tips and Tricks would be nice in the wiki too, such as:
1) How to integrate with Silverlining
2) How to integrate with CEGUI
3) How to integrate with a Generic OpenGL 3.3 core+ middleware
4) GPU Debugging tools HowTo (CodeXL, NSight, apitrace, etc.)

Troubleshooting and FAQ pages.

**Comment by manhnt9** [comment]
I will add a CEGUI example as soon as possible.

**Comment by devshgraphicsprogramming** [comment]
cegui could be an irr::ext

**Comment by manhnt9** [comment]
Only if we really port CEGUI's IrrlichtRenderer from Irrlicht 1.8.4 to IrrlichtBAW for better performance and interop. Needs a stable version. Anyways I haven't chatted with CEGUI team for a long time after contributing encrypted zip resource provider (all GUI stuffs can be archived with password). Will contact and urge them migrate to git for better future too, svn is sick.

A CEGUI example is expected to have minor changes at initialization and some render calls, then figuring out which states can be ignored seems to be tricky for me.

**Comment by devshgraphicsprogramming** [comment]
wiki is bad, proper Sphinx docs better
