### ISSUE TITLE
Linux example build errors

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#274]
I don't know if @devshgraphicsprogramming touched the CMake or not.
But before adding the unit test for sRGB branch, Linux build is fine.
Now it seems like CMake can't find zlib of 3rdparty anymore. I also cleared build folder and tried several times.

[100%] Linking CXX executable ../../../examples_tests/08.HardwareInstancing/bin/hardwareinstancing
../../3rdparty/libpng/libpng16.a(pngwrite.c.o):pngwrite.c:function png_image_write_init: error: undefined reference to 'deflateEnd'
../../3rdparty/libpng/libpng16.a(pngwrite.c.o):pngwrite.c:function png_destroy_write_struct: error: undefined reference to 'deflateEnd'
../../3rdparty/libpng/libpng16.a(pngwutil.c.o):pngwutil.c:function png_deflate_claim: error: undefined reference to 'deflateEnd'
../../3rdparty/libpng/libpng16.a(pngwutil.c.o):pngwutil.c:function png_deflate_claim: error: undefined reference to 'deflateInit2_'
../../3rdparty/libpng/libpng16.a(pngwutil.c.o):pngwutil.c:function png_deflate_claim: error: undefined reference to 'deflateReset'
../../3rdparty/libpng/libpng16.a(pngwutil.c.o):pngwutil.c:function png_text_compress: error: undefined reference to 'deflate'
../../3rdparty/libpng/libpng16.a(pngwutil.c.o):pngwutil.c:function png_text_compress: error: undefined reference to 'deflate'
../../3rdparty/libpng/libpng16.a(pngwutil.c.o):pngwutil.c:function png_compress_IDAT: error: undefined reference to 'deflate'
../../3rdparty/libpng/libpng16.a(pngwutil.c.o):pngwutil.c:function png_write_finish_row: error: undefined reference to 'deflate'
collect2: error: ld returned 1 exit status
examples_tests/08.HardwareInstancing/CMakeFiles/hardwareinstancing.dir/build.make:105: recipe for target '../examples_tests/08.HardwareInstancing/bin/hardwareinstancing' failed
make[2]: *** [../examples_tests/08.HardwareInstancing/bin/hardwareinstancing] Error 1
CMakeFiles/Makefile2:3520: recipe for target 'examples_tests/08.HardwareInstancing/CMakeFiles/hardwareinstancing.dir/all' failed
make[1]: *** [examples_tests/08.HardwareInstancing/CMakeFiles/hardwareinstancing.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by manhnt9** [comment]
Weird, I have to `$<TARGET_OBJECTS:zlib>` to png_static. Not required before ...

**Comment by manhnt9** [comment]
I'm afraid I'd have to say that our CMake may not be stable. Moving to CMake 3.13+ (getting rid of variables) is recommended. In my project I import built libraries as targets and all works well.

**Comment by manhnt9** [comment]
For examples these are variables and considered not good in modern CMake:
```shell
if (UNIX)
	target_include_directories(Irrlicht PUBLIC 
		${X11_INCLUDE_DIR} 
		${X11_Xrandr_INCLUDE_PATH} 
		${X11_xf86vmode_INCLUDE_PATH})
endif()

if (UNIX)
	target_link_libraries(Irrlicht INTERFACE 
		${X11_LIBRARIES} 
		${X11_Xrandr_LIB} 
		${X11_Xxf86vm_LIB} 
		${CMAKE_THREAD_LIBS_INIT}
		${CMAKE_DL_LIBS}
	)
endif()
```

Lib should be seen as object (target in CMake) containing its own properties like include path, lib file. That way we only need single CMake command to add a lib to target. Like: `target_link_libraries(target PUBLIC/PRIVATE lib)`. No need to set include path.

**Comment by manhnt9** [comment]
Real example:
- saga_obj lib depends on several libs: https://gitlab.com/InnerPieceOSS/Saga3D/blob/master/library/CMakeLists.txt#L41
- Saga3D::Library (things should lie in a namespace for public user) represents the main lib: https://gitlab.com/InnerPieceOSS/Saga3D/blob/master/library/CMakeLists.txt#L49
- samples link to Saga3D::Library and have all dependencies together: https://gitlab.com/InnerPieceOSS/Saga3D/blob/master/samples/functions.cmake#L7

**Comment by manhnt9** [comment]
Current build error:
IrrlichtBAW/source/Irrlicht/CFileSystem.cpp:895:13: error: ‘access’ was not declared in this scope
     return (access(filename.c_str(), 0) != -1);

**Comment by devshgraphicsprogramming** [comment]
@Crisspl was supposed to fix the whole Linux build system this weekend.

We've had an issue with one of your CMake changes breaking the Windows build (PNG or ZLIB target).

**Comment by manhnt9** [comment]
OK, I acknowledged that and was going to disable the exceptions in build after seeing utfcpp's updates but met this blocker. So I think I'd have to wait more.

**Comment by manhnt9** [comment]
After a little digging I find out that the issue is caused by Linux platform defines are not enabled.

**Comment by Crisspl** [comment]
That's fixed in my linux-build branch but still not ready build iwth PCH
Probably that's what you're about, there was a typo in #define for Linux build in IrrCompileConfig

**Comment by manhnt9** [comment]
Cool, can you merge it into sRGB branch for me to start some of my issues?

**Comment by devshgraphicsprogramming** [comment]
done
