### ISSUE TITLE
BRDF Explorer Rendering Implementation

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#276]
People Concered: @manhnt9 @Crisspl @Florastamine

This is a stub issue, we will discuss how to go about implementing the BRDF Explorer spec.

**Comment by devshgraphicsprogramming** [comment]
To be named `13.BRDFExplorer`

**Comment by devshgraphicsprogramming** [comment]
Initial implementation should have all the points according to the Overleaf LaTeX specification, except for various BRDFs.

So we can test loading and swapping models, and only have a basic Lambertian BRDF with bump mapping and AO.

@manhnt9 questions?

**Comment by manhnt9** [comment]
Which AO algorithm will we use?

**Comment by devshgraphicsprogramming** [comment]
AO is a baked greyscale texture (in the GUI explorer) we just modulate the diffuse BRDF by it.

**Comment by manhnt9** [comment]
And bump mapping? Does it depend on https://github.com/buildaworldnet/IrrlichtBAW/issues/221?

**Comment by devshgraphicsprogramming** [comment]
Not at all, the meshes you'll be fed will have correct Normals and your tangent frame shall be derived from
http://www.thetenthplanet.de/archives/1180

Basically an improved (handles texture stretching and triangle mirroring) version of the original `dFdx` implicit bump-mapping I've taught you.

It is important that derivative maps and not Dot3 normal maps are used (and computed from greyscale bump map textures at runtime 😉 when those are loaded ).

We have been told explicitly to support double sided lighting in our shaders, so I need to clarify how to handle normals of back-facing triangles (which shall be visible, no culling).

**Comment by devshgraphicsprogramming** [comment]
Update: The handling of double sided lighting, the back faces shall flip their surface normals and do lighting according to that (a true double faced material).

**Comment by devshgraphicsprogramming** [comment]
@Crisspl is in charge of implementing functions for derivative mapping and a derivative map generation function (from heightmap)

**Comment by devshgraphicsprogramming** [comment]
Deriviative Mapping is not 100% pre-requisite, work can go in parallel before #301 is merged.

Any BRDF common glsl code can be refactored into headers at the end.

**Comment by devshgraphicsprogramming** [comment]
detailed spec coming

**Comment by devshgraphicsprogramming** [comment]
![brdf_explorer_d 2019-06-24 23-32-44-08](https://user-images.githubusercontent.com/6894321/60055603-6e5cea80-96de-11e9-89b3-e7f62b39e18d.png)

**Comment by devshgraphicsprogramming** [comment]
@Crisspl TODO:
- [x] Add uEmissive*AO to color regardless of light
- [x] Multiply AO map on top of diffuse
- [x] Change the Fresnel factor on Diffuse from `1.0-F(NdotH,ReIoR,ImIoR)` to `1.05*(1.0-F(VdotN,ReIoR,ImIoR))*(1.0-F(LdotN,ReIoR,ImIoR))` (should be 100% correct for smooth diffuse)
- [x] Make IoR slider into 3 real RGB sliders
- [x] Add 3 Complex IoR sliders
- [x] Use Height Correlated Smith GGX Masking Function
- [x] Check why OBJ importer gets Cerberus Normals wrong
- [x] Check materials (no INF and NaN pixels) work on parameter extremes
- [x] Make a nice (that renders nicely) Readme.md in the example's folder explaining how to use the app and how it works

Optional:
- [ ] Allow the user to choose between Orren-Nayar Diffuse, Hammon Multi-scattering Approximation or CoD WWII Approximation
- [x] Add Hammon optimized lerp-based Correlated Smith GGX approximation to the appropriate GLSL built-in header (without the numerator obvs)
- [ ] Add Conductor Fresnel (Imaginary IoR) Equation approximations from "PHARR,  M.,ANDHUMPHREYS,  G.   2010.Physically Based Rendering,  SecondEdition:  From Theory To Implementation"  mentioned in Ole Gulbrandsen's paper
- [ ] Add Direct Conductor Fresnel from Reflectance F0 and Edge-Tint approximation to Fresnel Approximation Header (along with Schlick) from Appendix A of Ole Gulbrandsen's paper
```cpp
f l o a t    f r e s n e l ( f l o a t    r ,    f l o a t   g , f l o a t    t h e t a ) {/ /clamp parametersf l o a t    _ r   =   c l a m p ( r , 0 , 0 . 9 9 ) ;/ /compute n and kf l o a t   n   =   g e t _ n ( _ r , g ) ;f l o a t   k2   =   g e t _ k 2 ( _ r , n ) ;f l o a t   c   =   c o s ( t h e t a ) ;r s _ n u m   =   n∗n   +   k2−2∗n∗c   +   c∗c ;r s _ d e n   =   n∗n   +   k2   +   2∗n∗c   +   c∗c ;r s   =   r s _ n u m / r s _ d e n ;rp_num   =   ( n∗n   +   k2 )∗c∗c−2∗n∗c   +   1 ;r p _ d e n   =   ( n∗n   +   k2 )∗c∗c   +   2∗n∗c   +   1 ;r p   =   rp_num / r p _ d e n ;r e t u r n    0 . 5∗( r s + r p ) ;}
```

**Comment by devshgraphicsprogramming** [comment]
@Crisspl progress?

**Comment by Crisspl** [comment]
most likely I won't be able to work tomorrow at all. All of non-optional TODOs + derivative mapping + anisotropic roughness will come in days 29june-04july.

**Comment by devshgraphicsprogramming** [comment]
@Crisspl add uEmissive*ao as the basic light (not done yet)

**Comment by Crisspl** [comment]
It's finished (all the required todos). I'll just do some prettyfying of usage today. Also there's some weird code in the engine always setting camera position to (10,0,0) at init, so I'll also have a look at it.

**Comment by devshgraphicsprogramming** [comment]
Congrats
