### ISSUE TITLE
Support Building on Clang

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#287]
Clang is now default Android compiler.

It is also a popular Linux compiler.

Right now it reports errors in aesGladman code.

**Comment by reachananya** [comment]
Can I work on it?

**Comment by devshgraphicsprogramming** [comment]
> 
> 
> Can I work on it?

Yes, we're currently fixing it up for GCC
https://github.com/Devsh-Graphics-Programming/Nabla/tree/gcc-fixes

**Comment by devshgraphicsprogramming** [comment]
as said, getting done in `gcc-fixes` branch
