### ISSUE TITLE
sRGB branch build errors, X11 related

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#288]
lzma submodule deinited and pulled

In file included from /home/manh/IrrlichtBAW/source/Irrlicht/CMeshSceneNodeInstanced.cpp:7:0:
/home/manh/IrrlichtBAW/source/Irrlicht/COpenGLDriver.h: At global scope:
/home/manh/IrrlichtBAW/source/Irrlicht/COpenGLDriver.h:678:17: error: ‘GLXContext’ does not name a type; did you mean ‘SAuxContext’?
                 GLXContext ctx;
                 ^~~~~~~~~~
                 SAuxContext
/home/manh/IrrlichtBAW/source/Irrlicht/COpenGLDriver.h:679:17: error: ‘GLXPbuffer’ does not name a type; did you mean ‘setbuffer’?
                 GLXPbuffer pbuff;
                 ^~~~~~~~~~
                 setbuffer
/home/manh/IrrlichtBAW/source/Irrlicht/COpenGLDriver.h:1004:4: error: ‘GLXDrawable’ does not name a type
    GLXDrawable Drawable;
    ^~~~~~~~~~~
/home/manh/IrrlichtBAW/source/Irrlicht/COpenGLDriver.h:1005:4: error: ‘Display’ does not name a type
    Display* X11Display;
    ^~~~~~~
/home/manh/IrrlichtBAW/source/Irrlicht/COpenGLDriver.h: In constructor ‘irr::video::COpenGLDriver::SAuxContext::SAuxContext()’:
/home/manh/IrrlichtBAW/source/Irrlicht/COpenGLDriver.h:637:58: error: class ‘irr::video::COpenGLDriver::SAuxContext’ does not have any field named ‘ctx’
             SAuxContext() : threadId(std::thread::id()), ctx(NULL), XFormFeedbackRunning(false), CurrentXFormFeedback(NULL),
                                                          ^~~
source/Irrlicht/CMakeFiles/Irrlicht.dir/build.make:335: recipe for target 'source/Irrlicht/CMakeFiles/Irrlicht.dir/CMeshSceneNodeInstanced.cpp.o' failed
make[2]: *** [source/Irrlicht/CMakeFiles/Irrlicht.dir/CMeshSceneNodeInstanced.cpp.o] Error 1
CMakeFiles/Makefile2:2867: recipe for target 'source/Irrlicht/CMakeFiles/Irrlicht.dir/all' failed
make[1]: *** [source/Irrlicht/CMakeFiles/Irrlicht.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by manhnt9** [comment]
Cleared the build folder and build again with PCH enabled, successfully.

But when run `make` in example_tests folder, I meet these:

/usr/bin/ld.gold: error: ../../source/Irrlicht/libIrrlicht.a(CSoftwareDriver2.cpp.o): multiple definition of 'irr::asset::ESStoShadercEnum(irr::asset::E_SHADER_STAGE)'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(Irrlicht.cpp.o): previous definition here
/usr/bin/ld.gold: error: ../../source/Irrlicht/libIrrlicht.a(CTRGouraud2.cpp.o): multiple definition of 'irr::asset::ESStoShadercEnum(irr::asset::E_SHADER_STAGE)'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(Irrlicht.cpp.o): previous definition here
/usr/bin/ld.gold: error: ../../source/Irrlicht/libIrrlicht.a(CTRTextureGouraud2.cpp.o): multiple definition of 'irr::asset::ESStoShadercEnum(irr::asset::E_SHADER_STAGE)'

**Comment by Crisspl** [comment]
Could you try making this function inline and I'll take a look at it in a moment? It's defined there https://github.com/Crisspl/IrrlichtBAW/blob/master/src/irr/asset/shadercUtils.h

**Comment by manhnt9** [comment]
Yep, that should be the solution I think. Trying it out.

**Comment by manhnt9** [comment]
That fixes the multiple definition errors. But something else comes up. Template bug I think.
(I already cleared the build folder and start over).

Building CXX object examples_tests/03.GPU_Mesh/CMakeFiles/gpu_mesh.dir/main.cpp.o
In file included from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irrlicht.h:50:0,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/main.cpp:2:
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/core/alloc/address_allocator_traits.h:26:49: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
         _IRR_STATIC_INLINE_CONSTEXPR uint32_t   invalid_address = 0xdeadbeefu;
                                                 ^~~~~~~~~~~~~~~
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/core/alloc/address_allocator_traits.h:33:49: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
         _IRR_STATIC_INLINE_CONSTEXPR uint64_t   invalid_address = 0xdeadbeefBADC0FFEull;
                                                 ^~~~~~~~~~~~~~~
In file included from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irrlicht.h:50:0,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/main.cpp:2:
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/core/alloc/address_allocator_traits.h:162:55: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
             _IRR_STATIC_INLINE_CONSTEXPR bool         supportsArbitraryOrderFrees = resolve_supportsArbitraryOrderFrees<AddressAlloc>::value;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/core/alloc/address_allocator_traits.h:163:55: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
             _IRR_STATIC_INLINE_CONSTEXPR uint32_t     maxMultiOps                 = resolve_maxMultiOps<AddressAlloc>::value;
                                                       ^~~~~~~~~~~
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/core/alloc/address_allocator_traits.h:164:55: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
             _IRR_STATIC_INLINE_CONSTEXPR bool         supportsNullBuffer          = resolve_supportsNullBuffer<AddressAlloc>::value;
                                                       ^~~~~~~~~~~~~~~~~~
In file included from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irrlicht.h:62:0,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/main.cpp:2:
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/core/alloc/MultiBufferingAllocatorBase.h:29:43: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
         _IRR_STATIC_INLINE_CONSTEXPR bool alwaysSwapEntireRange = true;
                                           ^~~~~~~~~~~~~~~~~~~~~
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/core/alloc/MultiBufferingAllocatorBase.h:52:43: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
         _IRR_STATIC_INLINE_CONSTEXPR bool alwaysSwapEntireRange = false;
                                           ^~~~~~~~~~~~~~~~~~~~~
In file included from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/SMaterial.h:8:0,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/asset/bawformat/CBAWFile.h:11,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/asset/ICPUMeshBuffer.h:7,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/asset/ICPUSkinnedMeshBuffer.h:8,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irrlicht.h:70,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/main.cpp:2:
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/vectorSIMD.h:261:80: warning: ignoring attributes on template argument ‘__m128i {aka __vector(2) long long int}’ [-Wignored-attributes]
     class vectorSIMD_32 : public SIMD_32bitSwizzleAble<vectorSIMD_32<T>,__m128i>, public impl::vectorSIMDIntBase<vectorSIMD_32<T> >
                                                                                ^
In file included from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/SMaterial.h:8:0,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/asset/bawformat/CBAWFile.h:11,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/asset/ICPUMeshBuffer.h:7,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/asset/ICPUSkinnedMeshBuffer.h:8,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irrlicht.h:70,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/main.cpp:2:
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/vectorSIMD.h:463:72: warning: ignoring attributes on template argument ‘__m128 {aka __vector(4) float}’ [-Wignored-attributes]
     class vectorSIMDf : public SIMD_32bitSwizzleAble<vectorSIMDf,__m128>, public AlignedBase<_IRR_VECTOR_ALIGNMENT>
                                                                        ^
In file included from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/IDriver.h:10:0,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/HostDeviceMirrorBufferAllocator.h:77,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irrlicht.h:93,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/main.cpp:2:
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/StreamingTransientDataBuffer.h: In instantiation of ‘void irr::video::StreamingTransientDataBufferST<_size_type, CPUAllocator, CustomDeferredFreeFunctor>::multi_free(Args&& ...) [with Args = {unsigned int, unsigned int*, unsigned int*, irr::video::IDriverFence*}; _size_type = unsigned int; CPUAllocator = irr::core::aligned_allocator<unsigned char, 16>; CustomDeferredFreeFunctor = void]’:
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/StreamingTransientDataBuffer.h:169:29:   required from ‘void irr::video::StreamingTransientDataBufferMT<_size_type, CPUAllocator, CustomDeferredFreeFunctor, RecursiveLockable>::multi_free(Args&& ...) [with Args = {unsigned int, unsigned int*, unsigned int*, irr::video::IDriverFence*}; _size_type = unsigned int; CPUAllocator = irr::core::aligned_allocator<unsigned char, 16>; CustomDeferredFreeFunctor = void; RecursiveLockable = std::recursive_mutex]’
IrrlichtBAW/examples_tests/03.GPU_Mesh/main.cpp:252:99:   required from here
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/StreamingTransientDataBuffer.h:90:29: error: no matching function for call to ‘irr::video::StreamingTransientDataBufferST<unsigned int, irr::core::aligned_allocator<unsigned char, 16>, void>::multi_free(unsigned int, unsigned int*, unsigned int*, irr::video::IDriverFence*)’
             Base::multi_free(std::forward<Args>(args)...);
             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/StreamingTransientDataBuffer.h:7:0,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/IDriver.h:10,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/HostDeviceMirrorBufferAllocator.h:77,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irrlicht.h:93,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/main.cpp:2:
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/SubAllocatedDataBuffer.h:226:29: note: candidate: void irr::video::SubAllocatedDataBuffer<HeterogenousMemoryAddressAllocator, CustomDeferredFreeFunctor>::multi_free(irr::core::smart_refctd_ptr<irr::video::IDriverFence>&&, irr::video::SubAllocatedDataBuffer<HeterogenousMemoryAddressAllocator, CustomDeferredFreeFunctor>::DeferredFreeFunctor&&) [with HeterogenousMemoryAddressAllocator = irr::core::HeterogenousMemoryAddressAllocatorAdaptor<irr::core::GeneralpurposeAddressAllocator<unsigned int, irr::core::impl::GeneralpurposeAddressAllocatorStrategy<unsigned int, false> >, irr::video::StreamingGPUBufferAllocator, irr::core::aligned_allocator<unsigned char, 16> >; CustomDeferredFreeFunctor = void; irr::video::SubAllocatedDataBuffer<HeterogenousMemoryAddressAllocator, CustomDeferredFreeFunctor>::DeferredFreeFunctor = irr::video::SubAllocatedDataBuffer<irr::core::HeterogenousMemoryAddressAllocatorAdaptor<irr::core::GeneralpurposeAddressAllocator<unsigned int, irr::core::impl::GeneralpurposeAddressAllocatorStrategy<unsigned int, false> >, irr::video::StreamingGPUBufferAllocator, irr::core::aligned_allocator<unsigned char, 16> >, void>::DefaultDeferredFreeFunctor]
         inline void         multi_free(core::smart_refctd_ptr<IDriverFence>&& fence, DeferredFreeFunctor&& functor) noexcept
                             ^~~~~~~~~~
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/SubAllocatedDataBuffer.h:226:29: note:   candidate expects 2 arguments, 4 provided
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/SubAllocatedDataBuffer.h:234:29: note: candidate: void irr::video::SubAllocatedDataBuffer<HeterogenousMemoryAddressAllocator, CustomDeferredFreeFunctor>::multi_free(uint32_t, const size_type*, const size_type*) [with HeterogenousMemoryAddressAllocator = irr::core::HeterogenousMemoryAddressAllocatorAdaptor<irr::core::GeneralpurposeAddressAllocator<unsigned int, irr::core::impl::GeneralpurposeAddressAllocatorStrategy<unsigned int, false> >, irr::video::StreamingGPUBufferAllocator, irr::core::aligned_allocator<unsigned char, 16> >; CustomDeferredFreeFunctor = void; uint32_t = unsigned int; irr::video::SubAllocatedDataBuffer<HeterogenousMemoryAddressAllocator, CustomDeferredFreeFunctor>::size_type = unsigned int]
         inline void         multi_free(uint32_t count, const size_type* addr, const size_type* bytes) noexcept
                             ^~~~~~~~~~
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/SubAllocatedDataBuffer.h:234:29: note:   candidate expects 3 arguments, 4 provided
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/SubAllocatedDataBuffer.h:243:29: note: candidate: template<class Q> void irr::video::SubAllocatedDataBuffer<HeterogenousMemoryAddressAllocator, CustomDeferredFreeFunctor>::multi_free(uint32_t, const size_type*, const size_type*, irr::core::smart_refctd_ptr<irr::video::IDriverFence>&&, typename std::enable_if<std::is_same<Q, irr::video::SubAllocatedDataBuffer<HeterogenousMemoryAddressAllocator, CustomDeferredFreeFunctor>::DefaultDeferredFreeFunctor>::value>::type*) [with Q = Q; HeterogenousMemoryAddressAllocator = irr::core::HeterogenousMemoryAddressAllocatorAdaptor<irr::core::GeneralpurposeAddressAllocator<unsigned int, irr::core::impl::GeneralpurposeAddressAllocatorStrategy<unsigned int, false> >, irr::video::StreamingGPUBufferAllocator, irr::core::aligned_allocator<unsigned char, 16> >; CustomDeferredFreeFunctor = void]
         inline void         multi_free(uint32_t count, const size_type* addr, const size_type* bytes, core::smart_refctd_ptr<IDriverFence>&& fence, typename std::enable_if<std::is_same<Q,DefaultDeferredFreeFunctor>::value>::type* = 0) noexcept
                             ^~~~~~~~~~
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/SubAllocatedDataBuffer.h:243:29: note:   template argument deduction/substitution failed:
In file included from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/IDriver.h:10:0,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/HostDeviceMirrorBufferAllocator.h:77,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irrlicht.h:93,
                 from IrrlichtBAW/examples_tests/03.GPU_Mesh/main.cpp:2:
IrrlichtBAW/examples_tests/03.GPU_Mesh/../../include/irr/video/StreamingTransientDataBuffer.h:90:29: note:   cannot convert ‘std::forward<irr::video::IDriverFence*>((* & args#3))’ (type ‘irr::video::IDriverFence*’) to type ‘irr::core::smart_refctd_ptr<irr::video::IDriverFence>&&’
             Base::multi_free(std::forward<Args>(args)...);
             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples_tests/03.GPU_Mesh/CMakeFiles/gpu_mesh.dir/build.make:62: recipe for target 'examples_tests/03.GPU_Mesh/CMakeFiles/gpu_mesh.dir/main.cpp.o' failed
make[2]: *** [examples_tests/03.GPU_Mesh/CMakeFiles/gpu_mesh.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:3240: recipe for target 'examples_tests/03.GPU_Mesh/CMakeFiles/gpu_mesh.dir/all' failed
make[1]: *** [examples_tests/03.GPU_Mesh/CMakeFiles/gpu_mesh.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Crisspl** [comment]
Hmm i think it's related to recent changes about RAII refctd ptr. @devshgraphicsprogramming?

**Comment by devshgraphicsprogramming** [comment]
the bugs that you have left after inlining the shaderUtils thing, yes those are from RAII.. sorry I did not test enough.

**Comment by Crisspl** [comment]
Just rebuilt meshloaders (and Irrlicht) on Linux and links fine (my master)

**Comment by devshgraphicsprogramming** [comment]
The examples afftected will be all the stuff that uses streaming buffer as the API has changed slightly.

**Comment by Crisspl** [comment]
Yep, still getting those errors mentioned by manh while building ex03 :/

**Comment by devshgraphicsprogramming** [comment]
minor stuff, got fixed
