### ISSUE TITLE
Save build time

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#293]
Currently, 3rdparty projects are included in main project generation. This causes:
- Long build time: VS ran through every dependencies again each build
- Solution explorer flood: too many projects to navigate and not necessary
- Build output flood

Same thing will happen for Linux.
I suggest only keeping subprojects that are directly related to irrbaw in project generation, such as convert2baw, etc.
Normally the dependencies should be built only once and left intact during the build process of main lib. If there's dependency change, we can just re-run CMake without any other hassle (VS will automatically detect changes and re-run CMake too).

I'm already integrating CEGUI that way, it builds when running CMake and does not affect library or example build. If this change is not considered applicable for some reason, I would have to change CEGUI build later.

**Comment by devshgraphicsprogramming** [comment]
I'm not entirely sure that "build when configuring" is a good call.

Because one might want to tweak the **configuration** of the 3rd-party dependencies before attempting an actual build.

I would however put forward the assertion that #196 will greatly improve build times, unless CMake loves to check dependencies recursively.

**Comment by manhnt9** [comment]
Somehow rebuilding between Debug and Release still takes a lot of time. It should have been cached by ccache like other parts. Maybe PCH or some config generated files don't play nice?

**Comment by manhnt9** [comment]
I've built both Release and Debug and here is the time to switch build config.
Build with Release: 2m4.628s
Build with Debug: 2m38.397s
I think ccache doesn't work with the main lib at all, it only caches for dependencies.

**Comment by devshgraphicsprogramming** [comment]
that is a very good build time, we never compiled sub 3 minutes before
(in fact before @Crisspl worked on the cmake last week Debug would have taken you in excess of an hour)

AFAIK there are separate PCHs for each configuration

**Comment by manhnt9** [comment]
I mean the ccache should work, this is not a clean build. Re-build should take just several seconds.

**Comment by devshgraphicsprogramming** [comment]
depends what you touch, if you touch a header then you need to rebuild several files.

Keep in mind that the biggest offender of build-time are the pixel conversion functions which bloat the library to a 150mb+ build

**Comment by manhnt9** [comment]
Well, I just re-build with different configuration.

**Comment by devshgraphicsprogramming** [comment]
@Crisspl we have 1 pch file per configuration (debug/Release), correct?

**Comment by devshgraphicsprogramming** [comment]
> 
> 
> Well, I just re-build with different configuration.

A change in configuration will force a total recompile since after each CMake configure a new configured header is made, timestamp changes, etc. and this is the top level header that controls the behaviour of all the other ones. So in essence the code for every compilation unit changes.
