### ISSUE TITLE
Linker errors on Linux with debug build

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#294]
The lib build is fine. For example build I get:
IrrlichtBAW/source/Irrlicht/coreutil.cpp:129: error: undefined reference to '_Ux86_64_getcontext'

**Comment by manhnt9** [comment]
@Crisspl @devshgraphicsprogramming I tried to render the GUI today but this happens:
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/COpenGLStateManager.h:530:32: error: ‘GL_CLIP_DISTANCE6’ was not declared in this scope
                         return GL_CLIP_DISTANCE6;

**Comment by manhnt9** [comment]
Full error log:

[100%] Building CXX object examples_tests/13.BRDF_Explorer/CMakeFiles/brdf_explorer.dir/__/__/ext/CEGUI/CEGUI.cpp.o
In file included from IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLExtensionHandler.h:19:0,
                 from IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLDriver.h:25,
                 from IrrlichtBAW/ext/CEGUI/CEGUI.cpp:29:
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/COpenGLStateManager.h: In static member function ‘static GLenum irr::video::COpenGLState::glEnableBitToGLenum(const uint64_t&)’:
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/COpenGLStateManager.h:530:32: error: ‘GL_CLIP_DISTANCE6’ was not declared in this scope
                         return GL_CLIP_DISTANCE6;
                                ^~~~~~~~~~~~~~~~~
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/COpenGLStateManager.h:530:32: note: suggested alternative: ‘GL_CLIP_DISTANCE0’
                         return GL_CLIP_DISTANCE6;
                                ^~~~~~~~~~~~~~~~~
                                GL_CLIP_DISTANCE0
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/COpenGLStateManager.h:533:32: error: ‘GL_CLIP_DISTANCE7’ was not declared in this scope
                         return GL_CLIP_DISTANCE7;
                                ^~~~~~~~~~~~~~~~~
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/COpenGLStateManager.h:533:32: note: suggested alternative: ‘GL_CLIP_DISTANCE0’
                         return GL_CLIP_DISTANCE7;
                                ^~~~~~~~~~~~~~~~~
                                GL_CLIP_DISTANCE0
In file included from IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLDriver.h:25:0,
                 from IrrlichtBAW/ext/CEGUI/CEGUI.cpp:29:
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLExtensionHandler.h: In static member function ‘static void irr::video::COpenGLExtensionHandler::extGlClearNamedFramebufferfv(GLuint, GLenum, GLint, const GLfloat*)’:
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLExtensionHandler.h:3465:78: error: invalid conversion from ‘const GLfloat* {aka const float*}’ to ‘GLfloat* {aka float*}’ [-fpermissive]
             pGlClearNamedFramebufferfv(framebuffer, buffer, drawbuffer, value);
                                                                              ^
In file included from IrrlichtBAW/ext/CEGUI/CEGUI.cpp:29:0:
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLDriver.h: At global scope:
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLDriver.h:678:17: error: ‘GLXContext’ does not name a type; did you mean ‘SAuxContext’?
                 GLXContext ctx;
                 ^~~~~~~~~~
                 SAuxContext
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLDriver.h:679:17: error: ‘GLXPbuffer’ does not name a type; did you mean ‘setbuffer’?
                 GLXPbuffer pbuff;
                 ^~~~~~~~~~
                 setbuffer
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLDriver.h:1004:4: error: ‘GLXDrawable’ does not name a type
    GLXDrawable Drawable;
    ^~~~~~~~~~~
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLDriver.h:1005:4: error: ‘Display’ does not name a type
    Display* X11Display;
    ^~~~~~~
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLDriver.h: In constructor ‘irr::video::COpenGLDriver::SAuxContext::SAuxContext()’:
IrrlichtBAW/examples_tests/13.BRDF_Explorer/../../include/../source/Irrlicht/COpenGLDriver.h:637:58: error: class ‘irr::video::COpenGLDriver::SAuxContext’ does not have any field named ‘ctx’
             SAuxContext() : threadId(std::thread::id()), ctx(NULL), XFormFeedbackRunning(false), CurrentXFormFeedback(NULL),
                                                          ^~~
examples_tests/13.BRDF_Explorer/CMakeFiles/brdf_explorer.dir/build.make:75: recipe for target 'examples_tests/13.BRDF_Explorer/CMakeFiles/brdf_explorer.dir/__/__/ext/CEGUI/CEGUI.cpp.o' failed
make[2]: *** [examples_tests/13.BRDF_Explorer/CMakeFiles/brdf_explorer.dir/__/__/ext/CEGUI/CEGUI.cpp.o] Error 1
CMakeFiles/Makefile2:3874: recipe for target 'examples_tests/13.BRDF_Explorer/CMakeFiles/brdf_explorer.dir/all' failed
make[1]: *** [examples_tests/13.BRDF_Explorer/CMakeFiles/brdf_explorer.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Crisspl** [comment]
I made it to link to libunwind yesterday and tested on meshloaders example build (debug build) with engine and all deps from scratch. Builds fine so most likely it's something wrong in ex13 setup or generally your side

**Comment by manhnt9** [comment]
Could you try just including `COpenGLExtensionHandler.h` and build the helloworld example? The compile errors are for the lib actually, it does not point to my code. BTW I think this is because the OpenGL state tracking code is staying behind and not updated since the drop of Silverlining example.

**Comment by devshgraphicsprogramming** [comment]
it might be the project does not have the `./source/Irrlicht/` for the header include search paths, thats why you're probably not seeing stuff usually defined in glext.h

**Comment by devshgraphicsprogramming** [comment]
> ‘GL_CLIP_DISTANCE6’ was not declared in this scope

This is a define in glext.h (which is here https://github.com/buildaworldnet/IrrlichtBAW/blob/master/source/Irrlicht/glext.h )

**Comment by devshgraphicsprogramming** [comment]
> ple build I get:
> IrrlichtBAW/source/Irrlicht/coreutil.cpp:129: error: undefined reference to '_Ux86_64_getcontext'

Thats libunwind not being linked.

**Comment by manhnt9** [comment]
I've just tried the following in COpenGLDriver.h
```cpp
// also includes the OpenGL stuff
#include "glext.h"
#include "COpenGLExtensionHandler.h"
```
Still same errors.

**Comment by devshgraphicsprogramming** [comment]
I think it simply does not find these headers, try this after the includes
```c++
#ifndef __glext_h_
#error "Failed to find glext.h or not pulling in the defines"
#endif

#ifndef GL_VERSION_3_0
#error "Why is this not defined?"
#endif
```

Btw what order are you including OpenGL state manager and COpenGLExtensionHandler?

**Comment by manhnt9** [comment]
RFC from @devshgraphicsprogramming for this issue: https://github.com/Crisspl/IrrlichtBAW/commit/df448a29975eff96a8754d8bd74732edbeccc948 

Commit message:
Partial fixes for conflicts with GLEW
Unfortunately also commenting out the code in glew.h that produces 'gl.h was included from before GLEW' error or similar...
But generally most likely solution would be to make sure irrbaw's GL headers and GLEW's GL headers never end up in the same translation unit

**Comment by devshgraphicsprogramming** [comment]
then you need to keep CEGUI+GLEW separate from OpenGLStateManager, or sort out the order in which heaers get included.

We need to see more output regarding the errors.

I think the main "pain in the ass" comes from the fact that the last release of glew was in 2017 (2.1.0), whereas the last release of OpenGL 4.6 was in 2017, so we need to make sure that CEGUI is using the latest glew + opengl headers and that IrrBaW is also using the latest glext.h,wglext.h,glxext.h and gl.h

**Comment by devshgraphicsprogramming** [comment]
Maybe try "CEGUI_USE_EPOXY" instead of "CEGUI_USE_GLEW" ?

I see there are a lot of `find_package` for CEGUI CMake which is extremely annoying, maybe its finding an old glew with old glext.h headers ?

Since this is linux it will basically depend on what version of glew you have available in the repositories.

This is why I prefer all dependencies as submodules as not relying on package manager such as vcpkg, apt, etc. 

Because what version of the dependency is controlled by the OS or other tool global tool.

**Comment by manhnt9** [comment]
Solved, my assumption is right, just isolating the state management code and it will compile and run.

Different GLEW of CEGUI doesn't matter.
