### ISSUE TITLE
Having .gch in source dir

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#296]
Currently my sRGB branch produces these:

	source/Irrlicht/pch.h.gch
	source/Irrlicht/server_pch.h
	source/Irrlicht/server_pch.h.gch

**Comment by devshgraphicsprogramming** [comment]
After the latest merge into my sRGB branch from @Crisspl that should be gone.

those might be leftovers from the time you're had those files in gitignore

**Comment by manhnt9** [comment]
Removed those and tried rebuild, still has source/Irrlicht/server_pch.h

**Comment by Crisspl** [comment]
Yes, see this comment https://github.com/buildaworldnet/IrrlichtBAW/pull/291#discussion_r281785414

**Comment by manhnt9** [comment]
I think it should be generated in build folder instead of source folder.

**Comment by devshgraphicsprogramming** [comment]
thats exactly what I told @Crisspl to do.
