### ISSUE TITLE
Patch irr_adjust* macros to take effects on target only

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#298]
Currently the irr_adjust* macros set options for everything including subdir projects.
CEGUI needs exception enabled (without a kill switch) and we need to use `add_subdirectory` to support MSVC.

Those macros forbid exceptions for all projects then CEGUI is failed to build.
I've add temporary fix for this as: only enable exceptions when IRR_BUILD_CEGUI option is enabled. That also means all projects used in irrbaw aren't exceptions free.
Since it's caused by your macro code, I won't be able to support further.
I've tried every possible way to override compiler settings for subdir project and none works.

Suggested fix: Patch the irr_adjust* macros to take effects on each target only.
We can have multiple targets with exceptions or no-exceptions compile features.
Subdir project exposes targets so we can adjust them.

**Comment by devshgraphicsprogramming** [comment]
AFAIK:
- Irrlicht (core,video,asset,scene,etc) are their own library
- anything irr::ext is header only, collection of sources or a separate library
- examples link some combination of the above

So the flags for examples need to be derived from the options of the main Irr library +  any extensions.

If an extension needs to throw, fine... the exampe using it can also throw, we only really care about nothrow and other options for the main lib and examples which are supposed to be benchmarks.

**Comment by devshgraphicsprogramming** [comment]
@Crisspl  your thoughts on the suggested fix?

**Comment by manhnt9** [comment]
irr_adjust* macros overrides all compiler settings for dependencies as well, that's why CEGUI didn't compile and reported "enable -fexceptions to build". So the main point here is whichever target needs to be adjusted, adjust only for them with CMake's `target_*` commands.

**Comment by devshgraphicsprogramming** [comment]
ok, @Crisspl could you rework this?

(We still want all 3rdparty dependencies that are possible, to build with those options that we've been using so far, and the ones that can't to build with options as similar as can get... i.e. CEGUI with everything like `msse4.2` etc. but only without `fno-exceptions`)

**Comment by Crisspl** [comment]
Maybe it can be done by just reordering `add_subdirectory`s but, I haven't had a look yet. Priority?

**Comment by devshgraphicsprogramming** [comment]
~GLSL Include Handler > this > derivative mapping~

**Comment by devshgraphicsprogramming** [comment]
> 
> 
> Maybe it can be done by just reordering `add_subdirectory`s but, I haven't had a look yet. Priority?

That's not a valid or clean fix, that's a hack.

**Comment by Crisspl** [comment]
@manhnt9 do you know an easy way to remove compile option on per-target basis and for particular config? The thing is that targets get some shitty default options and cmake doesn't provide simple way to manipulate them (`target_compile_options` for adding only). Theoretically one can manipulate `COMPILE_OPTIONS` target's property (with `get_target_properties` and `set_target_properties`)  but it just doesn't work XD 
So yea, I hate CMake from now on

**Comment by devshgraphicsprogramming** [comment]
@Crisspl if you can't fix it in 1 hours work then move onto the next thing

**Comment by devshgraphicsprogramming** [comment]
Done by @AnastaZIuk

**Comment by manhnt9** [comment]
Great to know the progress !
Watching the new repo Nabla again.
