### ISSUE TITLE
Example doesn't trigger zlib build properly.

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#299]
![57843372-5b5e1d00-77f8-11e9-8eda-00e88f5d8b78](https://user-images.githubusercontent.com/11463928/57919978-23bca700-78c4-11e9-9bed-4e3beea4f87e.PNG)

This is caused by example not calling lib build first. I have to build Irrlicht.sln separately then open Example solution to build. It could be more convenient if user can just call CMake and go straight to the example build if they want to.

**Comment by manhnt9** [comment]
Imagine when you change example's config and Irrlicht hasn't been built with that config, one may spend hours to find out the problem.

**Comment by Crisspl** [comment]
>This is caused by example not calling lib build first. I have to build Irrlicht.sln separately then open Example solution to build.

Well.. it did. If it's not the case now, then something has changed

**Comment by manhnt9** [comment]
I see that. It still calls the Irrlicht build, but not completely.
Rebuilding example still rebuilds Irrlicht.
I think someone forgot to add all dependencies to Irrlicht when open Example.
In the image above OpenSSL is not built. 
I think the problem of this issue should be clarified as: Example build doesn't trigger all Irrlicht dependencies.

**Comment by Crisspl** [comment]
Could be a little problem in add_custom_command building openssl. CMake should be able to see whether openssl *.lib-s exist and if not, re-run openssl build. Can you take a look if it is the cause?

**Comment by Crisspl** [comment]
https://github.com/manhnt9/IrrlichtBAW/blob/sRGB/3rdparty/openssl/CMakeLists.txt

hm, nah, I think it's ok how it is

**Comment by manhnt9** [comment]
Try this and you'll see if it is a problem or not.
First case:
- Clear build folder
- Run cmake
- Open an example solution
- Build

Second case:
- After testing the first case, build config is probably Debug
- Switch example's config to Release
- Build

**Comment by Crisspl** [comment]
If you mean openssl should be built sperately for both configs then no - it is release build regardless of irrbaw's/examples' config

**Comment by devshgraphicsprogramming** [comment]
dependencies should be release builds/configs whenever possible, you don't want the whole library to be so slow in Debug mode that the OpenGL driver terminates the app to prevent a Denial of Service attack.

This is why we don't disable MSCV CRT Debug so that iterators and STL containers are not grinding the render loop to a halt.

**Comment by devshgraphicsprogramming** [comment]
> 
> 
> Try this and you'll see if it is a problem or not.
> First case:
> 
>     * Clear build folder
> 
>     * Run cmake
> 
>     * Open an example solution
> 
>     * Build
> 
> 
> Second case:
> 
>     * After testing the first case, build config is probably Debug
> 
>     * Switch example's config to Release
> 
>     * Build

but obviously the build shouldn't break when you switch configs ;)

**Comment by manhnt9** [comment]
As I reported the build error in the description of this issue, the general problem is it won't build Irrlicht properly when the build is triggered from Example solution. I had to build Irrlicht first then I can build Example. It happens only for the first time.

**Comment by devshgraphicsprogramming** [comment]
So if you've built Irrlicht before, then change irrlicht, then do an example build, it will work ok?

**Comment by manhnt9** [comment]
Not totally sure, gonna test in some mins.

**Comment by manhnt9** [comment]
Yes, it works. I think this issue affects OpenSSL only.

**Comment by manhnt9** [comment]
Well, this problem presents on Linux too. I clear build folder, run cmake and build example today on Flor's branch.

[100%] Built target Irrlicht
Scanning dependencies of target colorspacetest
make[2]: *** No rule to make target '3rdparty/CMakeFiles/zlib.dir/zlib/adler32.c.o', needed by '../examples_tests/09.ColorSpaceTest/bin/colorspacetest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[100%] Building CXX object examples_tests/09.ColorSpaceTest/CMakeFiles/colorspacetest.dir/main.cpp.o
CMakeFiles/Makefile2:3606: recipe for target 'examples_tests/09.ColorSpaceTest/CMakeFiles/colorspacetest.dir/all' failed
make[1]: *** [examples_tests/09.ColorSpaceTest/CMakeFiles/colorspacetest.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by devshgraphicsprogramming** [comment]
thats zlib dependency not OpenSSL, zlib seems needed by 3 or 4 dependencies, we add the subdirectory once... I have almost 0% CMake knowledge but this issue may stem from multiple dependencies wanting zlib

**Comment by devshgraphicsprogramming** [comment]
I think this was never about OpenSSL in the first place

**Comment by manhnt9** [comment]
As I remember about the old zlib issue, it didn't find out the lib to link to (zlib didn't present in the link list). This issue is about not finding the lib file.

**Comment by manhnt9** [comment]
After making this change, this issue seems to disappear:
```
+++ b/source/Irrlicht/CMakeLists.txt
@@ -271,6 +271,7 @@ add_library(Irrlicht STATIC
        $<TARGET_OBJECTS:convert_utf>
        $<TARGET_OBJECTS:lz4>
        $<TARGET_OBJECTS:lzma>
+       $<TARGET_OBJECTS:zlib>
        $<TARGET_OBJECTS:spirv_cross>
 )
```

but this comes up:

Linking CXX executable ../../../examples_tests/09.ColorSpaceTest/bin/colorspacetest
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/adler32.c.o: multiple definition of 'adler32_z'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(adler32.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/adler32.c.o: multiple definition of 'adler32'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(adler32.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/adler32.c.o: multiple definition of 'adler32_combine'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(adler32.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/adler32.c.o: multiple definition of 'adler32_combine64'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(adler32.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/crc32.c.o: multiple definition of 'get_crc_table'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(crc32.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/crc32.c.o: multiple definition of 'crc32_z'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(crc32.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/crc32.c.o: multiple definition of 'crc32'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(crc32.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/crc32.c.o: multiple definition of 'crc32_combine'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(crc32.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/crc32.c.o: multiple definition of 'crc32_combine64'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(crc32.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inffast.c.o: multiple definition of 'inflate_fast'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inffast.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateResetKeep'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateReset'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateReset2'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateInit2_'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateInit_'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflatePrime'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflate'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateEnd'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateGetDictionary'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateSetDictionary'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateGetHeader'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateSync'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateSyncPoint'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateCopy'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateUndermine'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateValidate'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateMark'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inflate.c.o: multiple definition of 'inflateCodesUsed'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inflate.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inftrees.c.o: multiple definition of 'inflate_table'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inftrees.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/inftrees.c.o: multiple definition of 'inflate_copyright'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(inftrees.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/zutil.c.o: multiple definition of 'zlibVersion'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(zutil.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/zutil.c.o: multiple definition of 'zlibCompileFlags'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(zutil.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/zutil.c.o: multiple definition of 'zError'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(zutil.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/zutil.c.o: multiple definition of 'z_errmsg'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(zutil.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/zutil.c.o: multiple definition of 'zcalloc'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(zutil.c.o): previous definition here
/usr/bin/ld.gold: error: ../../3rdparty/CMakeFiles/zlib.dir/zlib/zutil.c.o: multiple definition of 'zcfree'
/usr/bin/ld.gold: ../../source/Irrlicht/libIrrlicht.a(zutil.c.o): previous definition here
collect2: error: ld returned 1 exit status
examples_tests/09.ColorSpaceTest/CMakeFiles/colorspacetest.dir/build.make:115: recipe for target '../examples_tests/09.ColorSpaceTest/bin/colorspacetest' failed
make[2]: *** [../examples_tests/09.ColorSpaceTest/bin/colorspacetest] Error 1
CMakeFiles/Makefile2:3607: recipe for target 'examples_tests/09.ColorSpaceTest/CMakeFiles/colorspacetest.dir/all' failed
make[1]: *** [examples_tests/09.ColorSpaceTest/CMakeFiles/colorspacetest.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by manhnt9** [comment]
Somehow it links the example to zlib again although Irrlicht already links to zlib, but I only found 2 `$<TARGET_OBJECTS:zlib>` in the repo for Irrlicht and IrrlichtServer, which were reasonable. Finding out where does the example links zlib.

**Comment by manhnt9** [comment]
Found it, someone made libpng links to zlib too.
![Screenshot_2019-05-24_10-59-27](https://user-images.githubusercontent.com/11463928/58301993-054e3280-7e13-11e9-8fc3-3002b0e400d4.png)

**Comment by manhnt9** [comment]
OK, my conclusion is zlib build doesn't triggered properly even though libpng depends on it.
Then the macro `irr_target_link_libpng` is supposed to solve it when calling `irr_target_link_libpng(Irrlicht)` because the dependency chain should work, but sadly it doesn't. Honestly I don't know why though, maybe that's a glitch of variables. Breakdown:
- Our CMake set this: `set(ZLIB_LIBRARY "$<TARGET_OBJECTS:zlib>") #for pnglib`
- Apparently CMake can resolve this `ZLIB_LIBRARY` variable to the correct library when it says it needs a library from zlib
- This issue hasn't been discovered before since we hardly try building the example directly without building library itself first
- When adding zlib to Irrlicht's link libraries, the dependency chain works, zlib build is triggered, but then in Irrlicht and libpng also has zlib so the `multiple definitions` error above occurs
- So far I haven't succeeded in fixing it yet, tried including `add_dependencies` anywhere I can but it doesn't solve

**Comment by manhnt9** [comment]
Another suspicion is that CMake's code is not doing what we want, there're some unknown differences between:
- Building the library alone (zlib still builds)
- Attach Irrlicht projects to the example (zlib fails somehow)

**Comment by devshgraphicsprogramming** [comment]
Seems that Irrlicht links zlib and so does libpng, while libpng is linked into Irrlicht, that would give you a multiple definition when trying to link anything that uses Irrlicht

**Comment by devshgraphicsprogramming** [comment]
Hehe, I've found why this is a problem, and its really funny.

If you look at the MSVC solution explorer of any example, or extension... you will not see a `zlib` target in any of them. However the fact that an adler32 (zlib libs) needs to be linked is known and the correct paths to it and the zlib includes are provided. But the `zlib` project is nowhere to be found.

If you look at the MSVC solution explorer of `Irrlicht` then you will find a `zlib` target there, but it will only be built when you build **the entire solution**. If you make `Irrlicht` the "start-up project" or just click on it and just choose to "Build Irrlicht" then `zlib` will not get built.

Hence, `zlib` target/project is not being added as a proper dependency of `Irrlicht` or `libpng` (an `Irrlicht` dependency) or anything like that.

**Comment by Crisspl** [comment]
libpng didn't get zlib as dependency. Fixed in https://github.com/Crisspl/IrrlichtBAW/commit/aa76ca1054d2a2a3f6cab620408ef53e353f77f5

**Comment by devshgraphicsprogramming** [comment]
done
