### ISSUE TITLE
Blitting API doesn't allow selecting read-buffer

### ISSUE THREAD

**Issue by Crisspl** [buildaworldnet/IrrlichtBAW#339]
I think blitting/framebuffer API needs some adjustments. There's no way to specify read-buffer (so it's always default color attachment 0 for FBOs or backbuffer for default FB).
Also I found a little bug: calculation of read-region (intersection) takes into account *all* color attachments, but should only the one selected as read-buffer. It kind of depends on the proposed adjustments so I couldn't just fix it in the moment.

Posting because most likely some API-change decisions have to be taken.

**Comment by devshgraphicsprogramming** [comment]
that API is candidate for removal, whatever we replace it with better follow Vulkan model
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkCmdBlitImage.html
