### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#37]
Something maybe following this template

https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by raub** [comment]
link broken

**Comment by Crisspl** [comment]
You have to copy address because github put different address to actual link. Or just properly format link with markdown :D

**Comment by devshgraphicsprogramming** [comment]
believe it or now I actually used markdown the first time around

**Comment by devshgraphicsprogramming** [comment]
The wiki build instructions should really move to README
