### ISSUE TITLE
Update "Building The Library" at wiki section

### ISSUE THREAD

**Issue by AnastaZIuk** [buildaworldnet/IrrlichtBAW#371]
I've got some troubles with compiling engine using properly settings "--recurse-submodules" or using manually "git submodule init", "git submodule update" so far
There were no files in submodules, scripts have failed and had to use "git reset --hard" on each submodule to bring back valid commits
Please consider updating the Building The Library section with those informations

**Comment by devshgraphicsprogramming** [comment]
you can edit yourself AFAIK

**Comment by AnastaZIuk** [comment]
> you can edit yourself AFAIK

right, I didn't know though :D
done
