### ISSUE TITLE
Rework Color Format Conversion using GLI and possibly glut

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#38]
Completing the ECF_ enum table and conversions.

**Comment by devshgraphicsprogramming** [comment]
`void IVideoDriver::convertColor(const void* sP, ECOLOR_FORMAT sF, int32_t sN,
void* dP, ECOLOR_FORMAT dF) const` should find a new home and be a template function of color formats.

**Comment by devshgraphicsprogramming** [comment]
oh boy, dont we have a lot of formats

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkFormat.html

**Comment by devshgraphicsprogramming** [comment]
`VK_FORMAT*` should have matching ECF_ enumerations

There is a `isFormatCompressed` which should be moved simply into the `video` namespace
Also a number of helper functions like `getCompressed***BlockSize` should get removed and replaced with `video::getTexelOrBlockSize`

https://github.com/buildaworldnet/IrrlichtBAW/blob/master/include/IVideoCapabilityReporter.h should report whether the particular instance supports a given color format (OpenGL supports a lesser subset than Vk 1.1, and even then vk 1.1. only supports certain formats sometimes)

**Comment by devshgraphicsprogramming** [comment]
I would recommend defining colour conversions as:
`template<ECOLOR_FORMAT sF, ECOLOR_FORMAT dF> inline convertColor(const void* srcPix, void* dstPix)`
where the srcPix and dstPix are assumed to be multiples of entire texels/blocks for uncompressed and compressed formats respectively. The general non-specialized function would get the output format block-size (1x1 for uncompressed), decode the input pixels to the highest precision available (64bit per-channel) of signed/unsigned/double-floating-point with `template<ECOLOR_FORMAT fmt, typename T> inline void decodePixels(const void* pixels, T* outValues)` (only implemented for T=`uint64_t`,`int64_t`,`double`).
Then the highest precision decoded input will get encoded into the destination format with `template<ECOLOR_FORMAT fmt, typename T> inline void encodePixels(const T* inValues, void* outBlockTexel)` (same conditions on T).

So our function would look more or less like this:
```
template<ECOLOR_FORMAT sF, ECOLOR_FORMAT dF>
inline convertColor(const void* srcPix, void* dstPix)
{
	typedef pixelPrecisionFmt ...; // whatever you need; uint64_t, int64_t, double

	uint64_t someStackSpace[LARGEST_BLOCK_SIZE_X*LARGEST_BLOCK_SIZE_Y*LARGEST_BLOCK_SIZE_Z][4]; // decode and encode already know the pitch sizes from the defines
	// some control loop
	{
		// a number of calls to
		decodePixels<sF>(srcPix+inBlockOffset,someStackSpace+outOffset);
	}
	// another control loop
	{
		// a number of calls to
		encodePixels<dF>(someStackSpace+inOffset,dstPix+outBlockOffset);
	}
}
```
There would be an obvious issue of when you'd have a format with a 4x4x1 block size and another with a 16x2x1 block size, etc., then you'd need to find the greatest common divisor of the input and output block size for every axis (and `LARGEST_BLOCK_SIZE_` would be the maximum out of that). Then the `convertColor` functions (static templated and dynamic) would assume that `srcPix` and `dstPix` point to enough blocks.
Maybe an `inline void getConversionFootprint(ECOLOR_FORMAT sF, ECOLOR_FORMAT dF, uint32_t footprintSize[3])` function would be handy to know how far the conversion function will advance for a combination of two formats.

Then the run-time function could either be massive switch statement (or a function call to a pointer from an array of function pointers) built in two stages:
```
namespace impl {
	template<ECOLOR_FORMAT sF>
	inline void convertColor_Impl(const void* sP, void* dP, ECOLOR_FORMAT dF)
	{
		switch (dF)
		{
			...
			case ECF_XYZ;
				convertColor<sF,ECF_XYZ>(sP,dP);
				break;
			...
		}
	}
}

inline void convertColor(const void* sP, ECOLOR_FORMAT sF, void* dP, ECOLOR_FORMAT dF)
{
	switch (sF)
	{
		...
		case ECF_XYZ;
			impl::convertColor_Impl<ECF_XYZ>(sP,dP,dF);
			break;
		...
	}
}
```

I personally think that a switch statement (maybe populated from a #preprocessor MACRO) is a better aproach as it requires no global table to populate (and hence invoke and instantiate every specialization),
an inline function could be optimized out by the compiler to not instantiate every template function.


Finally the specialization approach allows us to explicitly specialize certain format conversions, such as RGB8 to RGBA8 or R16F to R64F, without resolving to higher precision formats or dealing with more channels than necessary.

**Comment by devshgraphicsprogramming** [comment]
Also due to patent issues decodes and encodes to certain formats should and could not be implemented so the specializations should have a run-time assert inside.

ASTC is not patented but hard to implement, so maybe a `bool isImplementedInSoftware(ECOLOR_FORMAT fmt)` function could bein order.

P.S. BC1 to BC3 (also known as DXTn and S3TC) are no longer covered by patents.

**Comment by devshgraphicsprogramming** [comment]
Minimum level of functionality is to support everything that `void IVideoDriver::convertColor(const void* sP, ECOLOR_FORMAT sF, int32_t sN, void* dP, ECOLOR_FORMAT dF) const` supports right now

**Comment by devshgraphicsprogramming** [comment]
@Crisspl some questions:
1. Is the E_FORMAT enumeration is full and complete?
2. Are the driver format support queries done (vertex, FBO attachment, storage image, etc.) to parity with what can be queried from Vulkan Hardware Database?

**Comment by Crisspl** [comment]
1. Depends on whether you want E_FORMAT to include ETC2 and EAC formats even though we don't use them at all (license). Probably yes (since ASTC has similar situation and it got its place in the enum), so i'll add it in incoming commits.
2. No, it was lacking something. See your comments in newest commits of my `format` branch and you'll know what is it :P

**Comment by devshgraphicsprogramming** [comment]
> Depends on whether you want E_FORMAT to include ETC2 and EAC formats even though we don't use them at all (license). Probably yes (since ASTC has similar situation and it got its place in the enum), so i'll add it in incoming commits.

I dont want software decode encode, just the enum so I can update raw format-compatible data to OpenGL/Vulkan block compressed texture.

**Comment by devshgraphicsprogramming** [comment]
> No, it was lacking something. See your comments in newest commits of my format branch and you'll know what is it :P

Can you find the "something"

**Comment by Crisspl** [comment]
>Can you find the "something"

https://github.com/Crisspl/IrrlichtBAW/commit/b01d2989207a7c0263b12faad06436763cb5750a#r31620282
https://github.com/Crisspl/IrrlichtBAW/commit/b01d2989207a7c0263b12faad06436763cb5750a#r31620277

**Comment by devshgraphicsprogramming** [comment]
Done pending merge
