### ISSUE TITLE
BSDF Importance Sampling Validation

### ISSUE THREAD

**Issue by achalpandeyy** [buildaworldnet/IrrlichtBAW#382]
A simple utility to validate that the formulae used for the 3 functions needed for integration using Multiple Importance Sampling are consistent for every observer position (above and below the surface):

1. The BSDF probability density function over a full sphere (known as `eval` in Cycles)
2. The BSDF importance sampling function that transforms uniformly distributed random numbers in `[0,1]^2` into some distribution X (known as `sample` in Cycles)
3. The probability density function of X that will be used for MIS weights

The application will allow the user to open their own text file with GLSL language definitions of the 3 functions (with fixed BSDF parameters to constants) and produce a 2D image mapped to a surface of a sphere produced by splatting `GL_POINTS` using additive blending the intensity of function `3` in positions determined by function `2` and will compare the RMSE against the analytical evaluation of function `1`.

This will not be anything groundbreaking in itself, more like a Unit Test for the functions we will use in the Mitsuba Scene Rendering application.

**Comment by devshgraphicsprogramming** [comment]
Current examples that validate importance sampling via derivatives work just fine.
