### ISSUE TITLE
Transparency issues persist on Mesh Loaders and in hardware skinning example.

### ISSUE THREAD

**Issue by bkeys** [buildaworldnet/IrrlichtBAW#4]
There seems to be a window transparency issue going on in multiple examples, as can be seen on these screenshots, combined with my other issue this is 3 different examples that all have this problem.
![dwarfs](https://cloud.githubusercontent.com/assets/12195202/20707850/3cec4962-b5fb-11e6-81fd-9f5cbbfe298e.png)
![mesh loaders](https://cloud.githubusercontent.com/assets/12195202/20707853/3f5677f4-b5fb-11e6-8914-14ada00dfc0d.png)
As you can see in the dwarf's example the frame rates are rather low, with the discrete GPU I am now using, it should be very fast. Is there any other known issues with Irrlicht + Nvidia GPU's?

**Comment by devshgraphicsprogramming** [comment]
Latest commit will fix this (in 3 days)
