### ISSUE TITLE
Image Filters Bugs

### ISSUE THREAD

**Issue by AnastaZIuk** [buildaworldnet/IrrlichtBAW#460]
### List is for gathering found bugs and documenting them. 

Map:

- _Unsolved_: bugs that still need to be fixed
- _Probability of bugs_: those ones are suspected of being bugs, but they are not confirmed

**If you found a bug or you suspect something to be a bug, put your description here in following way**:

- short description of the target
- error compilation code if it's a syntax error
- link to appropriate line on github

In case of probability of being a bug, you won't pass error compile code, but you have to describe in a detail what's wrong and what's going on.

_Unsolved_:

_Probability of bugs_:

1. Copying regions with multilayered and mipmaped images. ImageView data is filled with black value and that's what renderDoc sees. ImageView is returned from GLI Loader which passes region validation, but probably there is something wrong while performing `cpu2gpu` conversion somewhere in `copybuffertoimage`.

_Fixed_:
1. `CState *` to `const Swizzle &` conversion
2. https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L120
and
https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L191

**Comment by devshgraphicsprogramming** [comment]
> Copying regions with multilayered and mipmaped images. ImageView data is filled with black value and that's what renderDoc sees. ImageView is returned from GLI Loader which passes region validation, but probably there is something wrong while performing cpu2gpu conversion somewhere in copybuffertoimage.

I need a concrete reproducible example

**Comment by devshgraphicsprogramming** [comment]
`CState` bug fixed

**Comment by AnastaZIuk** [comment]
Another one `CState *` to `const Swizzle &` conversion bug
```
Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	C2664	'void irr::asset::convertColor<irr::asset::EF_R8_SRGB,irr::asset::EF_R8G8B8_SRGB,Swizzle>(const void *[],void *,uint32_t,uint32_t,const Swizzle &)': cannot convert argument 5 from 'irr::asset::impl::CSwizzleAndConvertImageFilterBase<Swizzle>::CState *' to 'const Swizzle &'	Irrlicht	C:\work\IrrlichtBaw\IrrlichtBAW parallel work\include\irr\asset\filters	C:\work\IrrlichtBaw\IrrlichtBAW parallel work\include\irr\asset\filters\CSwizzleAndConvertImageFilter.h	157	
```
link: https://github.com/buildaworldnet/IrrlichtBAW/blob/image_manipulator/include/irr/asset/filters/CSwizzleAndConvertImageFilter.h#L157

**Comment by AnastaZIuk** [comment]
`CState*` parameter incompatibility 
```
Severity	Code	Description	Project	Path	File	Line	Suppression State
Error (active)	E0167	argument of type "irr::asset::impl::CSwizzleAndConvertImageFilterBase<irr::asset::PolymorphicSwizzle>::CState *" is incompatible with parameter of type "irr::asset::impl::CSwizzleAndConvertImageFilterBase<irr::asset::PolymorphicSwizzle>::CState *"	Irrlicht	C:\work\IrrlichtBaw\IrrlichtBAW parallel work\include\irr\asset\filters	C:\work\IrrlichtBaw\IrrlichtBAW parallel work\include\irr\asset\filters\CSwizzleAndConvertImageFilter.h	69	
```
link: https://github.com/buildaworldnet/IrrlichtBAW/blob/image_manipulator/include/irr/asset/filters/CSwizzleAndConvertImageFilter.h#L69

**Comment by devshgraphicsprogramming** [comment]
how can I provoke them?

**Comment by AnastaZIuk** [comment]
@devshgraphicsprogramming calls:

copy filter:
https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L83

convert filter:

https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L120

https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L191

https://github.com/Crisspl/IrrlichtBAW/pull/32/files#diff-eb2dc54b0c55978bb914855feb4a7255R32

https://github.com/Crisspl/IrrlichtBAW/pull/32/files#diff-93991be5497ff93db177bfe829ca6f07R63

https://github.com/Crisspl/IrrlichtBAW/pull/32/files#diff-c60d97d960d7645e1936db58c4a2469eR102

**Comment by devshgraphicsprogramming** [comment]
@AnastaZIuk this works without issue

https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L83

**Comment by devshgraphicsprogramming** [comment]
@AnastaZIuk 
https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L120
and
https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L191

fixed in latest commit


and those links dont work
https://github.com/Crisspl/IrrlichtBAW/pull/32/files#diff-eb2dc54b0c55978bb914855feb4a7255R32

https://github.com/Crisspl/IrrlichtBAW/pull/32/files#diff-93991be5497ff93db177bfe829ca6f07R63

https://github.com/Crisspl/IrrlichtBAW/pull/32/files#diff-c60d97d960d7645e1936db58c4a2469eR102

**Comment by AnastaZIuk** [comment]
> @AnastaZIuk
> https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L120
> and
> https://github.com/Crisspl/IrrlichtBAW/blob/5274cf63c26491483f61215f351f255e49f3df2e/include/irr/asset/IImageAssetHandlerBase.h#L191
> 
> fixed in latest commit
> 
> and those links dont work
> https://github.com/Crisspl/IrrlichtBAW/pull/32/files#diff-eb2dc54b0c55978bb914855feb4a7255R32
> 
> https://github.com/Crisspl/IrrlichtBAW/pull/32/files#diff-93991be5497ff93db177bfe829ca6f07R63
> 
> https://github.com/Crisspl/IrrlichtBAW/pull/32/files#diff-c60d97d960d7645e1936db58c4a2469eR102

it compiles now

**Comment by devshgraphicsprogramming** [comment]
so how do I reproduce GLI bug?

**Comment by AnastaZIuk** [comment]
> so how do I reproduce GLI bug?

Uh my dear, now I've been testing all applied filters in writers and loaders. When everything will be clean, then you will have again a clear and ready to use example 09 to figure out what's wrong with GLI bug

**Comment by AnastaZIuk** [comment]
@devshgraphicsprogramming you can track my branch, GLI left https://github.com/Crisspl/IrrlichtBAW/pull/32

**Comment by AnastaZIuk** [comment]
component  mapping doesn't work in swizzle and convert filter

**Comment by AnastaZIuk** [comment]
![image](https://user-images.githubusercontent.com/34793522/80218596-b079f400-8641-11ea-8eda-cd73965b073e.png) 
above there is an `array_r8_uint.dds` image that is being displayed and saved as screen shot correctly, but in priciple the writer doesn't write texel data, everything is black somehow. I deleted the file and now we use `R8_1_unorm`, but the behaviour is the same

![image](https://user-images.githubusercontent.com/34793522/80218990-385ffe00-8642-11ea-8bd1-d85eee417100.png)

bug can be fixed after pushing new changes to color space by me

**Comment by devshgraphicsprogramming** [comment]
what's the status of the GLI bug @AnastaZIuk  ?

**Comment by devshgraphicsprogramming** [comment]
@AnastaZIuk canwe close?

**Comment by AnastaZIuk** [comment]
I will try to tell you tomorrow

**Comment by AnastaZIuk** [comment]
gotta check it

**Comment by devshgraphicsprogramming** [comment]
and?

**Comment by AnastaZIuk** [comment]
Fixed image swizzling https://github.com/buildaworldnet/IrrlichtBAW/pull/529/commits/22015e6ee3558d8cc0162a757603cc09e8d9125f

**Comment by AnastaZIuk** [comment]
> and?

and it has worked since some corrections
![image](https://user-images.githubusercontent.com/34793522/90889611-c497ed00-e3b8-11ea-8b2f-fb9e87cc4c97.png)

**Comment by AnastaZIuk** [comment]
There is a weird pixels behaviour on bottom and right while using **CBlitFilter**
![image](https://user-images.githubusercontent.com/34793522/91718562-e866ea00-eb93-11ea-8fad-e5a5fa094548.png)
Checked on latest Criss' mitsuba commit where no changes by new filters API are applied to blit filter https://github.com/buildaworldnet/IrrlichtBAW/pull/424/commits/bd1502681c93e47ec66dba8787416d55021a675e

**Comment by devshgraphicsprogramming** [comment]
@AnastaZIuk this still a thing? Can you check on Nabla's `master` branch and prepare a repro?

**Comment by devshgraphicsprogramming** [comment]
> There is a weird pixels behaviour on bottom and right while using **CBlitFilter**
> ![image](https://user-images.githubusercontent.com/34793522/91718562-e866ea00-eb93-11ea-8fad-e5a5fa094548.png)
> Checked on latest Criss' mitsuba commit where no changes by new filters API are applied to blit filter [bd15026](https://github.com/buildaworldnet/IrrlichtBAW/commit/bd1502681c93e47ec66dba8787416d55021a675e)

this might be what @achalpandeyy found during his polyphase work
