### ISSUE TITLE
dynamic_array::data() should return properly aligned pointer

### ISSUE THREAD

**Issue by Crisspl** [buildaworldnet/IrrlichtBAW#481]
Just so we dont forget to fix this.
Problem is that pointer returned by `data()` doesnt obey alignment dictated by `allocator` (allocator type given as template param). 
Easiest and alignment-agnostic approach would be to store metadata (current `dynamic_array_base`) at the end of allocated memory block, but then there's a problem with accessing it because object doesn't really know where its members are XD
Second one i came up with is run-time value of `dummy_item_count` (currently is constexpr). Once `dynamic_array` is allocated, we can figure the alignment out from `this` pointer. Don't even store it, just compute with every call to `data()`. Ofc deduced alignment might be much bigger than actual alignment used by allocator, so probably we should have some max_supported_alignment constant.

**Comment by devshgraphicsprogramming** [comment]
ok will look into fixing
