### ISSUE TITLE
Mesh packer V1

### ISSUE THREAD

**Issue by Crisspl** [buildaworldnet/IrrlichtBAW#535]
Left TODO:
- [ ] triangle reordering - triangles sorted by area and "locality" in space (use 3d morton code for the latter)
- [ ] auto conversion into `TRIANGLE_LIST`
- [ ] fix bug of creating triangles with vertices of two different meshes. Usually happens when `minAllocSize` is set at low values
- [ ] handle per-instance attribs
- [ ] addr space shrink - IMO basically it should work like: first alloc everything, then create buffers with size just enough to fit allocated space, commit
- [ ] put asserts on things that shouldnt happen, everywhere (alloc, commit...)
- [ ] some more complex tests

**Comment by devshgraphicsprogramming** [comment]
> use 3d morton code for the latter

I actually suggested kind-of truncating morton codes depending on triangle size, so we're doing both at the same time.
