### ISSUE TITLE
List dependencies on github properly or use submodules

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#56]
https://help.github.com/articles/listing-the-packages-that-a-repository-depends-on/

**Comment by devshgraphicsprogramming** [comment]
Actually since this is a C++ project, maybe json deps are not supported?

So use submodules instead?
https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/

**Comment by devshgraphicsprogramming** [comment]
@Crisspl maybe use submodules for the shaderc stuff?

**Comment by Crisspl** [comment]
Why not, good idea

**Comment by manhnt9** [comment]
Possible if the github repo is in steady development.

**Comment by Crisspl** [comment]
Ehh those things provided for shaderc are strictly for Linux. https://github.com/google/shaderc/blob/master/libshaderc/README.md
However luckily shaderc provides binaries from MSVC x64 build. So I think submodule won't give us anything good since approach of integrating shaderc into Irrlicht would be totally dependent on platform.

**Comment by devshgraphicsprogramming** [comment]
ok I see, regarding shaderc, is this an option

> If the external project uses CMake, then shaderc/CMakeLists.txt can be included into the external project's CMake configuration and shaderc can be used as a link target. This is the simplest way to use libshaderc in an external project.

> If the external project uses CMake and is building for Linux or Android, target_link_libraries(shaderc_combined) can instead be specified. This is functionally identical to the previous option.

?

**Comment by devshgraphicsprogramming** [comment]
We should probably move all the 3rdparty libraries like lzma,zlib,etc. (with exception of openssl) from `./source/Irrlicht` to `./3rdparty` and make them git-submodules if an official git repository can be found or an unofficial but well-maintained one can be found.

@khom-khun want to do this on the `shaders` branch of @Crisspl ?

**Comment by devshgraphicsprogramming** [comment]
Done
