### ISSUE TITLE
Linux build system

### ISSUE THREAD

**Issue by numberZero** [buildaworldnet/IrrlichtBAW#66]
What’s about using [CMake](https://cmake.org/) as build system for Linux? (It actually works on other platforms, too.) It supports different compilers, automatic dependency management and makefile generation (or project file generation, if requested), and much more—virtually everything a build system needs. I have some experience with it, may convert CodeBlocks project to CMake easily; would you want such PR?

**Comment by devshgraphicsprogramming** [comment]
Sure but only if you don't end up renaming and moving all our source files as bkeys once did.

Note, the Visual Studio Project would have to be 1:1 recreated with parity to what we have now (except for windows SDK version).
Same goes for the Irrlicht.cbp project .

There are lots of nice compiler flags which unlock either performance or debug juice, and if CMake missed them we'd be in a very sad place.

The actual Makefile present in the repository right now is useless except for a BAW_SERVER build target which creates a version of the library with only a dummy CNullDriver (for machines with literally 0 GPU capability to render anything or open a window).

**Comment by devshgraphicsprogramming** [comment]
Pulled from @numberZero
